#TITLE=10.English
#INFO
New Cliptext library
#SORT=n

#T=【口语】“拍马屁”用语 
1. Wow 哇！(叫绝声) 
2. Way To Go 就该这么做 
3. Super 极好的 
4. You're Special 你不一般 
5. Outstanding 杰出的 
6. Excellent 优秀的 
7. Great 伟大的 
8. Good 好的 
9. Neat 真整洁 
10. Well Done 做得好 
11. Remarkable 非凡的 
12. I Knew You Could Do It 我知道你能做的 
13. I'm Proud Of You 我为你而骄傲 
14. Fantastic 太奇妙了 
15. Super Star 超级明星 
16. Nice Work 干得好 
17. Looking Good 看上去不错 
18. You're On Top Of It 你是数一数二的 
19. Beautiful 美极了 
20. Now You're Flying 现在你起飞了(进步了) 
21. You're Catching On 你是有吸引力的 
22. Now You've Got It 现在你做到了 
23. You're Incredible 你简直难以置信 
24. You Can Do It 你能做到 
25. How Did You Do That? 你怎样完成的？ 

#T=26句实用的英语
1. After you. 你先请。
这是一句很常用的客套话，在进／出门,上车得场合你都可以表现一下。 

2. I just couldn't help it. 我就是忍不住。
想想看，这样一个漂亮的句子可用于多少个场合？下面是随意举的一个例子：
I was deeply moved by the film and I cried and cried. I just couldn't help it. 

3. Don't take it to heart. 别往心里去，别为此而忧虑伤神。
生活实例：This test isn't that important. Don't take it to heart. 

4. We'd better be off. 我们该走了。It's getting late. We'd better be off . 

5. Let's face it. 面对现实吧。常表明说话人不愿意逃避困难的现状。
参考例句：I know it's a difficult situation. Let's face it, OK? 

6. Let's get started. 咱们开始干吧。
劝导别人时说：Don't just talk. Let's get started. 

7. I'm really dead. 我真要累死了。
坦诚自己的感受时说：After all that work, I'm really dead. 

8. I've done my best. 我已尽力了。

9. Is that so? 真是那样吗？常用在一个人听了一件事后表示惊讶、怀疑。

10. Don't play games with me! 别跟我耍花招！

11. I don't know for sure. 我不确切知道。例如：
Stranger：Could you tell me how to get to the town hall? 
Tom：I don't know for sure. Maybe you could ask the policeman over there. 

12. I'm not going to kid you. 我不是跟你开玩笑的。 例如：
Karin：You quit the job? You are kidding.
 Jack：I'm not going to kid you. I'm serious. 

13. That's something. 太好了，太棒了。例如：
A：I'm granted a full scholarship for this semester. 
B：Congratulations. That's something. 

14. Brilliant idea! 这主意真棒！这主意真高明！ 

15. Do you really mean it? 此话当真？例如：
Michael：Whenever you are short of money, just come to me. 
David：Do you really mean it? 

16. You are a great help. 你帮了大忙。

17. I couldn't be more sure. 我再也肯定不过。 

18. I am behind you. 我支持你。
 Whatever decision you're going to make, I am behind you. 

19. I'm broke. 我身无分文。

20. Mind you! 请注意！听着！(也可仅用Mind。) 
模范例句：Mind you! He's a very nice fellow though bad-tempered. 

21. You can count on it. 你尽管相信好了，尽管放心。例如：
A：Do you think he will come to my birthday party? 
B：You can count on it. 

22. I never liked it anyway. 我一直不太喜欢这东西。
当朋友或同事不小心摔坏你的东西时就可以用上这句话给他一个台阶，打破尴尬局面：Oh, don't worry. I'm thinking of buying a new one. I never liked it anyway. 

23. That depends. 看情况再说。例如：
I may go to the airport to meet her. But that depends. 

24. Congratulations. 恭喜你，祝贺你。

25. Thanks anyway. 无论如何我还是得谢谢你。当别人尽力要帮助你却没帮成时，你就可以用这个短语表示谢意。

26. It's a deal. 一言为定。
Harry：Haven't seen you for ages. Let's have a get-together next week. 
Jenny：It's a deal. 


#T=奥巴马就职演讲全文(未删节版)
奥巴马就职演讲全文(未删节版)
我的同胞们：
我今天站在这里，以谦卑的心情面对着在我面前的使命，对于你们赋予我的信任心存感激，也不敢遗忘开国先贤们所作的牺牲。我感谢布什总统为我们国家所作的服务、以及在政权交接过程中他所展示的大度及合作。
到现在已经有44位美国人进行了总统就职宣誓。这些言辞在繁荣兴旺时以及和平时期作出。但是，也有一些时期，这些誓言是在阴云密布和暴风雨来袭时作出。在这些时期里，美国继续向前行，不单单是身为总统者的睿智和远见，也是因为我们身为人民者仍然忠于开国先贤们的理想、以及忠实执行开国时的文件宣言。
所以，世代一直是如此的。所以我们这一代的美国人也必须如此。
我们现在非常了解我们正处于危机之中。我们的国家正在作战状态，对抗一个暴力和仇恨的广大网络。我们的经济大大受到削弱，这不仅是一些人贪婪和不负责任的后果，也是我们在做出艰难抉择，为国家进入新时代进行准备方面的共同失误所使然。房屋失去了；工作机会流失了；商业陷入凋敝的困境。我们的医疗费用过于昂贵；我们有太多的学校令人失望；每天都有更多的证据显示，我们使用能源的方式只能令我们的对手变强，同时威胁到我们的星球。
这些就是危机的信号，数据和统计结果都显示出来。数字不容易显示出来的、但是却不容忽视的是，我们全国各地有些信心正在消蚀，担心的是美国的衰落不可避免，担心我们的下一代不得不降低对未来的期许。
今天我要对你们说的是，我们面临的挑战是真实的。这些挑战不仅严峻，而且复杂。应对这些挑战绝非易事，更非一朝一夕之功。但是，美国，请明白这一点：这些挑战将会面对。
我们今天聚集在一起，因为我们选择了希望而不是恐惧，选择了众志成城而不是纷争不和。
我们今天共同来宣布，让心胸狭窄的怨言和虚妄的诺言成为过去，结束相互指责和攻击以及令人厌倦的教条，这些已经窒息压制我们的政治太过长久。
我们仍然还是一个年青的国家，不过用圣经的话来说，抛弃幼稚东西的时间已经到了。现在，我们要彰显美国的持久精神，创造新的历史，继承和发扬代代传承的珍贵才智和崇高的理想：那就是上帝赋予我们的，人人平等，人人自由，人人都有机会寻求最大幸福。
重申我们国家伟大的同时，我们深深懂得，伟大从来不是与生具来的。它必须努力赢得；我们的道路从来没有捷径，也没有妥协。我们的道路从来不是懦夫们所走的，也不是给那些喜欢轻松，或者喜欢追逐财富和名誉的人走的。而是给那些不畏风险的人、脚踏实地的实践者、那些发明创造者。带领我们走向繁荣和自由的漫长崎岖之路的前进者之中，有些有名声的人，但是更多的是工作中默默无闻的男女大众。
为了我们，他们背起简单的行囊，飘洋过海，寻求新的生活。
为了我们，他们在血汗车间和作坊中辛勤劳作，并且在美国的西部扎下根，他们忍受皮鞭的抽打，在坚硬的土地上辛勤耕作。
为了我们， 他们在康科德和盖底斯堡，在诺曼底和溪山出生入死地战斗。
为了我们能够过上好日子，我们的这些男女大众，前仆后继，英勇奋斗，不懈牺牲，直到他们的双手粗糙地磨出老茧；他们看到的美国是一个理想高于个人雄心壮志的国家，他们把美国的理想看得高于个人的生死，高于财富和派别。
这就是我们今天要继续进行的旅程。我们依然是世界上最繁荣、最强大的国家；我们劳工的创造力并没有比这场危机开始的时候低；我们的思想也没有缺乏创造性；对我们产品和服务的需求，也没有比上个星期或者上个月或者上一年减少；我们的能力依然没有减弱；但是，我们那种一成不变，保护狭隘利益，推出不受欢迎决策的时代注定已经成为过去。从今天开始， 我们将重新鼓舞，揩干净身上的灰尘，重新开始重新创造美国的任务。
放眼四周，到处是需要从事的工作，目前的经济状况需要我们迅速采取果敢的行动，我们将行动起来，不仅要创造就业机会，而且还要为今后的发展奠定基础。我们将修路架桥，架设电力网线，修建通往商务和连接民众的数据通道。我们将恢复科学应有的正确位置。利用科技奇迹提高医疗保健的质量，同时降低成本。为了能为我们的车辆和工厂提供能源，我们要进一步利用阳光，风力和土壤。我们要改造学校和大学，满足新时代的要求；我们有能力完成上述任务，我们一定能够完成上述任务。
现在，有些人对我们的雄心壮志表示怀疑，他们说，我们的体制不可能让我们实现这么多的宏伟计划。这些人的记忆实在太糟了。
因为他们忘记了这个国家过去已经取得的成就，忘记了当自由的男男女女的想象力为了共同目标而激励、而聚集在一起的时候，能够达成些什么。
这些冷嘲热讽的人不可能理解的是，他们脚下的这片土地已经发生了变化，长期以来耗尽我们精力的无聊的政治辩论已经不复存在。我们今天要问的，不是我们的政府是否太大或者太小，而是我们的政府是否起到作用，是否帮助美国家庭找到一份像样收入的工作，能够支付起医疗保险，一个有尊严的退休生活。如果回答是肯定的，我们就应该继续执行。如果回答是否定的，那么计划将会停止，那些负责管理公共资金的人应该负起责任。我们的支出必须睿智，必须改变坏习气，运作必须光明正大。只有这样，才能恢复美国人民和政府之间至关重要的信任。
市场到底是好的还是坏的力量，这也不是我们面临的问题。市场给人们带来的财富和扩大自由的力量是无可比拟的。但是目前的金融危机提醒我们，如果缺乏监督，市场可能会失去控制。如果一个国家只追求繁荣，繁荣是不可能长久的。美国经济之所以成功并不总是因为我们国内生产总值的规模，而是因为经济繁荣已经渗透到各个领域和层次，是因为我们有能力向一切愿意接受帮助的人提供机会。我们帮助其他国家不是出于慈善，而是因为这是达到我们共同利益最可靠的途径。
至于我们的共同防御，我们认为在我们的安全和理想之间做出选择是错误的。我们的建国先贤们在面对难以想象的危险的时候，他们起草了一份确保法制和人权的宪章，一份后来用几代人的鲜血发展的宪章。他们的理念如今依然照亮着全世界，我们不应该为了权宜之计而放弃。今天，观看这场就职典礼的世界各地的所有人民和政府，无论是在大都市，还是我父亲出生的小村庄，都知道，美国是所有追求和平与尊严的国家和人民的朋友，美国已做好准备，将再次成为世界领导人。
回想前辈们通过牢固的盟友和坚定的信念，而不是导弹和坦克，来面对法西斯主义和共产主义。他们明白，仅靠我们单独的力量是不能保卫我们自己的，而且我们也无权随心所欲要做我们想做的事情。他们知道只有通过明智的使用力量，力量才会增强，只有通过我们正义的信念、自身的榜样，以及具有人道主义和自我克制的温和素质，才会有国家的安全。
我们是这些美国传统的保持人，在这些原则再一次的指引下，通过各国之间更好的合作、理解和更多的努力，我们能够面对那些新的威胁。我们将开始负责任地撤离伊拉克，把伊拉克交给她的人民，并且巩固得来不易的阿富汗和平。我们将跟老朋友和从前的对手在一起，不辞辛劳地来减少核威胁，减少全球温室效应。我们不会为我们的生活方式而道歉，也不会放弃保卫这种生活方式。那些通过恐怖主义和屠杀无辜的方式来达到目的的人，我们现在要对你们说，我们的信念比以前更加强壮，是坚不可摧的，你们不会比我们更长久，我们一定会打败你们。
因为我们知道，多元化的传统是我们强点，而不是弱点。我们是一个由基督教和穆斯林、犹太教和印度教以及无信仰者组成的国家，我们是由来自地球每个角落的各种语言和文化组成的；因为我们承受过内战和种族隔离的痛苦洗礼，走出黑暗的历程，我们更加坚强，更加团结。我们不得不相信，以前的仇恨总有一天会过去，派别分歧迟早会消失。随着世界在变小，我们共有的人道主义精神一定会展示出来，美国一定要率先走进新的和平纪元。
针对穆斯林世界，我们要在相互有利和相互尊重的基础上，寻找新的推动方式；针对那些企图制造冲突，或者把自己的社会问题推卸给西方的各国领导人，要知道，你们的人民会用你的建设成就，而不是摧毁能力来评判你；针对那些通过腐败、欺骗和镇压异议人士来维持权力的人，要知道你们是在错误的历史一边；不过只要你们愿意放开拳头，我们愿意向你们伸出手。
针对那些贫穷国家，我们保证和你们一起工作，让你们的土地肥沃，让清水长流；我们会滋养饥饿的身躯，灌输饥渴的头脑。针对那些和我们一样相对富足的国家，我们要说，对我们境外的痛苦，我们再不能无动于衷了，在消耗世界资源的同时，我们不能不考虑后果。因为世界已经改变了，我们也一定要随之改变。
当我们思考未来的道路，我们要带着谦卑的感恩之心，牢牢记住那些勇敢的美国人，他们现在正在遥远的沙漠和山脉执行巡逻任务。他们今天有话要告诉我们，就像安葬在阿灵顿那些逝去的英雄一直对我们低语一样。我们向他们致敬，不只是因为他们捍卫我们的自由，他们更落实了服务的精神，他们愿意寻找比自己意义更重大的事情。在这个时刻，这个将定义整个时代的时刻，正是这样的精神，必须长存在我们心中。
不论政府能够或者需要做什么，这个国家最终仰赖的还是美国人民的信仰和决心。在堤坝决堤的时候，接纳一个陌生人所展现的仁慈；因为不愿意看到朋友失业，而宁愿减少自己的工时所展现的无私，这些美德帮助我们度过最黑暗的时间。消防队员冲进满是浓烟的楼梯间所展现的勇气；父母教养孩子展现的自发性，这些最终决定了我们的命运。
我们的挑战或许是全新的。我们解决的方式也可能是全新的。但是我们的成功所仰赖的价值观却是恒古不变的，这些价值观是辛勤工作、诚实、勇气、公平、宽容和好奇。这些是真实的。在历史上，这些是推动我们前进的宁静力量。现在需要的是回归这些真理。我们现在需要的一个新的责任世纪。每一个美国人都要认清，我们对我们自己、我们的国家、世界都有义务。我们不是勉强的接受这些义务，而是欢欣的接纳。我们坚定的知道，没有什么比为艰难的任务全力付出更能满足我们的精神，更能定义我们的特质。
这是公民权的代价和承诺。
这是我们自信的泉源。我们知道神召唤我们为了要塑造这个充满变动的未来。
这是我们的自由和信仰的意义，这说明了为什么不同种族和信仰的男女和幼童相聚在这个宏伟的广场上；这说明了为什么一个当他的父亲在不到60年前或许还不能在餐厅里接受服务的人，今天能够在你们面前，许下这个最神圣的誓言。
让我们以这样的态度纪念这一天：我们记得自己是谁，我们前进了多远。在美国诞生的年代，在最寒冷的月份，一小群爱国者在冰冻的河岸上，蜷缩在将熄的营火旁。那时，首都被遗弃了。敌人正在向前推进。白雪上沾染了鲜血。当时，我们革命的结果遭受最大的怀疑，但我们的建国之父命令要对人民宣读这些文字：
"让未来的世界知道，在寒冷的冬天，这个只有希望和美德能够生存的时候，受到一个共同危机挑战的城市和国家，曾经勇敢的面对他。"
美国。面对我们共同的危机，在这个艰苦的严冬，让我们记得这些永恒的字句。带着希望和美德，我们再次勇敢的面对冰冷的激流，承受未来可能降临的风暴。让我们的下一代传颂，当我们受到考验的时候，我们拒绝结束这场旅程。我们没有回头，也没有步履蹒跚。我们的眼光定在地平线上，神的恩典顾及我们，我们带着一份伟大的礼物，也就是自由，向前进，然后将这份礼物安全的交给未来的世世代代。
谢谢大家!
上帝保佑你们!
上帝保佑美国!
　　奥巴马就职演说英文全文如下：
　　My fellow citizens:
　　I stand here today humbled by the task before us, grateful for the trust you have bestowed, mindful of the sacrifices borne by our ancestors. I thank President Bush for his service to our nation, as well as the generosity and cooperation he has shown throughout this transition.
　　Forty-four Americans have now taken the presidential oath. The words have been spoken during rising tides of prosperity and the still waters of peace. Yet, every so often the oath is taken amidst gathering clouds and raging storms. At these moments, America has carried on not simply because of the skill or vision of those in high office, but because we the people have remained faithful to the ideals of our forebears, and true to our founding documents.
　　So it has been. So it must be with this generation of Americans.
　　That we are in the midst of crisis is now well understood. Our nation is at war, against a far-reaching network of violence and hatred. Our economy is badly weakened, a consequence of greed and irresponsibility on the part of some, but also our collective failure to make hard choices and prepare the nation for a new age. Homes have been lost; jobs shed; businesses shuttered. Our health care is too costly; our schools fail too many; and each day brings further evidence that the ways we use energy strengthen our adversaries and threaten our planet.
　　These are the indicators of crisis, subject to data and statistics. Less measurable but no less profound is a sapping of confidence across our land — a nagging fear that America''s decline is inevitable, and that the next generation must lower its sights.
　　Today I say to you that the challenges we face are real. They are serious and they are many. They will not be met easily or in a short span of time. But know this, America — they will be met.
　　On this day, we gather because we have chosen hope over fear, unity of purpose over conflict and discord.
　　On this day, we come to proclaim an end to the petty grievances and false promises, the recriminations and worn out dogmas, that for far too long have strangled our politics.
　　We remain a young nation, but in the words of scripture, the time has come to set aside childish things. The time has come to reaffirm our enduring spirit; to choose our better history; to carry forward that precious gift, that noble idea, passed on from generation to generation: the God-given promise that all are equal, all are free and all deserve a chance to pursue their full measure of happiness.
　　In reaffirming the greatness of our nation, we understand that greatness is never a given. It must be earned. Our journey has never been one of shortcuts or settling for less. It has not been the path for the faint-hearted — for those who prefer leisure over work, or seek only the pleasures of riches and fame. Rather, it has been the risk-takers, the doers, the makers of things — some celebrated but more often men and women obscure in their labor, who have carried us up the long, rugged path towards prosperity and freedom.
　　For us, they packed up their few worldly possessions and traveled across oceans in search of a new life.
　　For us, they toiled in sweatshops and settled the West; endured the lash of the whip and plowed the hard earth.
　　For us, they fought and died, in places like Concord and Gettysburg; Normandy and Khe Sahn.
　　Time and again these men and women struggled and sacrificed and worked till their hands were raw so that we might live a better life. They saw America as bigger than the sum of our individual ambitions; greater than all the differences of birth or wealth or faction.
　　This is the journey we continue today. We remain the most prosperous, powerful nation on Earth. Our workers are no less productive than when this crisis began. Our minds are no less inventive, our goods and services no less needed than they were last week or last month or last year. Our capacity remains undiminished. But our time of standing pat, of protecting narrow interests and putting off unpleasant decisions — that time has surely passed. Starting today, we must pick ourselves up, dust ourselves off, and begin again the work of remaking America.
　　For everywhere we look, there is work to be done. The state of the economy calls for action, bold and swift, and we will act — not only to create new jobs, but to lay a new foundation for growth. We will build the roads and bridges, the electric grids and digital lines that feed our commerce and bind us together. We will restore science to its rightful place, and wield technology''s wonders to raise health care''s quality and lower its cost. We will harness the sun and the winds and the soil to fuel our cars and run our factories. And we will transform our schools and colleges and universities to meet the demands of a new age. All this we can do. And all this we will do.
Now, there are some who question the scale of our ambitions — who suggest that our system cannot tolerate too many big plans. Their memories are short. For they have forgotten what this country has already done; what free men and women can achieve when imagination is joined to common purpose, and necessity to courage. 
　　What the cynics fail to understand is that the ground has shifted beneath them — that the stale political arguments that have consumed us for so long no longer apply. The question we ask today is not whether our government is too big or too small, but whether it works — whether it helps families find jobs at a decent wage, care they can afford, a retirement that is dignified. Where the answer is yes, we intend to move forward. Where the answer is no, programs will end. And those of us who manage the public''s dollars will be held to account — to spend wisely, reform bad habits, and do our business in the light of day — because only then can we restore the vital trust between a people and their government.
　　Nor is the question before us whether the market is a force for good or ill. Its power to generate wealth and expand freedom is unmatched, but this crisis has reminded us that without a watchful eye, the market can spin out of control — and that a nation cannot prosper long when it favors only the prosperous. The success of our economy has always depended not just on the size of our gross domestic product, but on the reach of our prosperity; on our ability to extend opportunity to every willing heart — not out of charity, but because it is the surest route to our common good.
　　As for our common defense, we reject as false the choice between our safety and our ideals. Our founding fathers, faced with perils we can scarcely imagine, drafted a charter to assure the rule of law and the rights of man, a charter expanded by the blood of generations. Those ideals still light the world, and we will not give them up for expedience''s sake. And so to all other peoples and governments who are watching today, from the grandest capitals to the small village where my father was born: know that America is a friend of each nation and every man, woman, and child who seeks a future of peace and dignity, and that we are ready to lead once more.
　　Recall that earlier generations faced down fascism and communism not just with missiles and tanks, but with sturdy alliances and enduring convictions. They understood that our power alone cannot protect us, nor does it entitle us to do as we please. Instead, they knew that our power grows through its prudent use; our security emanates from the justness of our cause, the force of our example, the tempering qualities of humility and restraint.
　　We are the keepers of this legacy. Guided by these principles once more, we can meet those new threats that demand even greater effort — even greater cooperation and understanding between nations. We will begin to responsibly leave Iraq to its people, and forge a hard-earned peace in Afghanistan. With old friends and former foes, we will work tirelessly to lessen the nuclear threat, and roll back the specter of a warming planet. We will not apologize for our way of life, nor will we waver in its defense, and for those who seek to advance their aims by inducing terror and slaughtering innocents, we say to you now that our spirit is stronger and cannot be broken; you cannot outlast us, and we will defeat you.
　　For we know that our patchwork heritage is a strength, not a weakness. We are a nation of Christians and Muslims, Jews and Hindus — and non-believers. We are shaped by every language and culture, drawn from every end of this Earth; and because we have tasted the bitter swill of civil war and segregation, and emerged from that dark chapter stronger and more united, we cannot help but believe that the old hatreds shall someday pass; that the lines of tribe shall soon dissolve; that as the world grows smaller, our common humanity shall reveal itself; and that America must play its role in ushering in a new era of peace.
To the Muslim world, we seek a new way forward, based on mutual interest and mutual respect. To those leaders around the globe who seek to sow conflict, or blame their society''s ills on the West — know that your people will judge you on what you can build, not what you destroy. To those who cling to power through corruption and deceit and the silencing of dissent, know that you are on the wrong side of history; but that we will extend a hand if you are willing to unclench your fist. 
　　To the people of poor nations, we pledge to work alongside you to make your farms flourish and let clean waters flow; to nourish starved bodies and feed hungry minds. And to those nations like ours that enjoy relative plenty, we say we can no longer afford indifference to suffering outside our borders; nor can we consume the world''s resources without regard to effect. For the world has changed, and we must change with it.
　　As we consider the road that unfolds before us, we remember with humble gratitude those brave Americans who, at this very hour, patrol far-off deserts and distant mountains. They have something to tell us today, just as the fallen heroes who lie in Arlington whisper through the ages. We honor them not only because they are guardians of our liberty, but because they embody the spirit of service; a willingness to find meaning in something greater than themselves. And yet, at this moment — a moment that will define a generation — it is precisely this spirit that must inhabit us all.
　　For as much as government can do and must do, it is ultimately the faith and determination of the American people upon which this nation relies. It is the kindness to take in a stranger when the levees break, the selflessness of workers who would rather cut their hours than see a friend lose their job which sees us through our darkest hours. It is the firefighter''s courage to storm a stairway filled with smoke, but also a parent''s willingness to nurture a child, that finally decides our fate.
　　Our challenges may be new. The instruments with which we meet them may be new. But those values upon which our success depends — hard work and honesty, courage and fair play, tolerance and curiosity, loyalty and patriotism — these things are old. These things are true. They have been the quiet force of progress throughout our history. What is demanded then is a return to these truths. What is required of us now is a new era of responsibility — a recognition, on the part of every American, that we have duties to ourselves, our nation, and the world, duties that we do not grudgingly accept but rather seize gladly, firm in the knowledge that there is nothing so satisfying to the spirit, so defining of our character, than giving our all to a difficult task.
　　This is the price and the promise of citizenship.
　　This is the source of our confidence — the knowledge that God calls on us to shape an uncertain destiny.
　　This is the meaning of our liberty and our creed — why men and women and children of every race and every faith can join in celebration across this magnificent mall, and why a man whose father less than sixty years ago might not have been served at a local restaurant can now stand before you to take a most sacred oath.
　　So let us mark this day with remembrance, of who we are and how far we have traveled. In the year of America''s birth, in the coldest of months, a small band of patriots huddled by dying campfires on the shores of an icy river. The capital was abandoned. The enemy was advancing. The snow was stained with blood. At a moment when the outcome of our revolution was most in doubt, the father of our nation ordered these words be read to the people:
　　"Let it be told to the future world ... that in the depth of winter, when nothing but hope and virtue could survive...that the city and the country, alarmed at one common danger, came forth to meet (it)."
　　America, in the face of our common dangers, in this winter of our hardship, let us remember these timeless words. With hope and virtue, let us brave once more the icy currents, and endure what storms may come. Let it be said by our children''s children that when we were tested we refused to let this journey end, that we did not turn back nor did we falter; and with eyes fixed on the horizon and God''s grace upon us, we carried forth that great gift of freedom and delivered it safely to future generations.

#T=400句,你的口语绝对不成问题了
背完这400句,你的口语绝对不成问题了

1. I see.				我明白了。
2. I quit!				我不干了!
3. Let go!				放手!
4. Me too.				我也是。
5. My god!				天哪!
6. No way!				不行!
7. Come on.				来吧(赶快)
8. Hold on.				等一等。
9. I agree。				我同意。
10. Not bad.				还不错。
11. Not yet.				还没。
12. See you.				再见。
13. Shut up!				闭嘴!
14. So long.				再见。
15. Why not?				好呀! (为什么不呢?)
16. Allow me.				让我来。
17. Be quiet!				安静点!
18. Cheer up!				振作起来!
19. Good job!				做得好!
20. Have fun!				玩得开心!
21. How much?				多少钱?
22. I'm full.				我饱了。
23. I'm home.				我回来了。
24. I'm lost.				我迷路了。
25. My treat.				我请客。
26. So do I.				我也一样。
27. This way.				这边请。
28. After you.				您先。
29. Bless you!				祝福你!
30. Follow me.				跟我来。
31. Forget it!				休想! (算了!)
32. Good luck!				祝好运!
33. I decline!				我拒绝!
34. I promise.				我保证。
35. Of course!				当然了!
36. Slow down!				慢点!
37. Take care!				保重!
38. They hurt.				(伤口)疼。
39. Try again.				再试试。
40. Watch out!				当心。
41. What's up?				有什么事吗?
42. Be careful!				注意!
43. Bottoms up!				干杯(见底)!
44. Don't move!				不许动!
45. Guess what?				猜猜看?
46. I doubt it				我怀疑。
47. I think so.				我也这么想。
48. I'm single.				我是单身贵族。
49. Keep it up!				坚持下去!
50. Let me see.				让我想想。
51. Never mind.				不要紧。
52. No problem!				没问题!
53. That's all!				就这样!
54. Time is up.				时间快到了。
55. What's new?				有什么新鲜事吗?
56. Count me on				算上我。
57. Don't worry.			别担心。
58. Feel better?			好点了吗?
59. I love you!				我爱你!
60. I'm his fan.			我是他的影迷。
61. Is it yours?			这是你的吗?
62. That's neat.			这很好。
63. Are you sure?			你肯定吗?
64. Do l have to			非做不可吗?
65. He is my age.			他和我同岁。
66. Here you are.			给你。
67. No one knows.			没有人知道。
68. Take it easy.			别紧张。
69. What a pity!			太遗憾了!
70. Any thing else?			还要别的吗?
71. To be careful!			一定要小心!
72. Do me a favor?			帮个忙,好吗?
73. Help yourself.			别客气。
74. I'm on a diet.			我在节食。
75. Keep in Touch.			保持联络。
76. Time is money.			时间就是金钱。
77. Who's calling?			是哪一位?
78. You did right.			你做得对。
79. You set me up!			你出卖我!
80. Can I help you?			我能帮你吗?
81. Enjoy yourself!			祝你玩得开心!
82. Excuse me,Sir.			先生,对不起。
83. Give me a hand!			帮帮我!
84. How's it going?			怎么样?
85. I have no idea.			我没有头绪。
86. I just made it!			我做到了!
87. I'll see to it.			我会留意的。
88. I'm in a hurry!			我在赶时间!
89. It's her field.			这是她的本行。
90. It's up to you.			由你决定。
91. Just wonderful!			简直太棒了!
92. What about you?			你呢?
93. You owe me one.			你欠我一个人情。
94. You're welcome.			不客气。
95. Any day will do.			哪一天都行夕
96. Are you kidding?			你在开玩笑吧!
97. Congratulations!			祝贺你!
98. T can't help it.			我情不自禁。
99. I don't mean it.			我不是故意的。
100. I'll fix you Up.			我会帮你打点的
101. It sounds great!.			听起来很不错。
102. It's a fine day.			今天是个好天。
103. So far,So good.			目前还不错。
104. What time is it?			几点了?
105. You can make it!			你能做到!
106. Control yourself!			克制一下!
107. He came by train.			他乘火车来。
108. He is ill in bed.			他卧病在床。
109. He lacks courage.			他缺乏勇气。
110. How's everything?			一切还好吧?
111. I have no choice.			我别无选择。
112. I like ice-cream.			我喜欢吃冰淇淋。
113. I love this game.			我钟爱这项运动。
114. I'll try my best.			我尽力而为。
115. I'm On.				还不错。
104. What time is it?			几点了?
105. You can make it!			你能做到!
106. Control yourself!			克制一下!
107. He came by train.			他乘火车来。
108. He is ill in bed.			他卧病在床。
109. He lacks courage.			他缺乏勇气。
110. How's everything?			一切还好吧?
111. I have no choice.			我别无选择。
112. I like ice-cream.			我喜欢吃冰淇淋。
113. I love this game			我钟爱这项运动。
114. I'll try my best			我尽力而为。
115. I'm On your side.			我全力支持你。
116. Long time no see!			好久不见!
117. No pain,no gain.			不劳无获。
118. Well,it depends.			噢,这得看情况。
119. We're all for it.			我们全都同意。
120. What a good deal!			真便宜!
121. What should I do?			我该怎么办？
122. You asked for it!			你自讨苦吃!
123. You have my word.			我保证。
124. Believe it or not!			信不信由你!
125. Don't count on me.			别指望我。
126. Don't fall for it!			别上当!
127. Don't let me down.			别让我失望。
128. Easy come easy go.			来得容易,去得快。
129. I beg your pardon.			请你原谅。
130. I beg your pardon?			请您再说一遍(我没有听清)。
131. I'll be back soon.			我马上回来。
132. I'll check it out.			我去查查看。
133. It's a long story.		说来话长。
134. It's Sunday today. 今天是星期天。
135. Just wait and see! 等着瞧!
136. Make up your mind. 做个决定吧。
137. That's all I need.我就要这些。
138. The view is great. 景色多么漂亮!
139. The wall has ears.隔墙有耳。
140. There comes a bus. 汽车来了。
141. What day is today? 今天星期几?
142. What do you think? 你怎么认为？
143. Who told you that? 谁告诉你的?
144. Who's kicking off? 现在是谁在开球?
145. Yes,I suppose So.是的,我也这么认为。
146. You can't miss it 你一定能找到的。
147. Any messages for me? 有我的留言吗?
148. Don't be so modest. 别谦虚了。
149. Don't give me that! 少来这套!
150. He is a smart boy. 他是个小机灵鬼。
151. He is just a child.他只是个孩子。
152. I can't follow you. 我不懂你说的。
153. I felt sort of ill. 我感觉有点不适。
154. I have a good idea! 我有一个好主意。
155. It is growing cool.天气渐渐凉爽起来。
156. It seems all right. 看来这没问题。
157. It's going too far.太离谱了。
158. May I use your pen? 我可以用你的笔吗?
159. She had a bad cold.她患了重感冒。
160. That's a good idea. 这个主意真不错。
161. The answer is zero.白忙了。
162. What does she like? 她喜欢什么?
163. As soon as possible! 越快越好!
164. He can hardly speak. 他几乎说不出话来。
165. He always talks big.他总是吹牛。
166. He won an election. 他在选举中获胜。
167. I am a football fan.我是个足球迷。
168. If only I could fly. 要是我能飞就好了。
169. I'll be right there. 我马上就到。
170. I'll see you at six. 我六点钟见你。
171. IS it true or false? 这是对的还是错的?
172. Just read it for me. 就读给我听好了。
173. Knowledge is power. 知识就是力量。
174. Move out of my way! 让开!
175. Time is running out. 没时间了。
176. We are good friends. 我们是好朋友。
177. What's your trouble? 你哪儿不舒服?
178. You did fairly well! 你干得相当不错1
179. Clothes make the man. 人要衣装。
180. Did you miss the bus? 你错过公共汽车了?
181. Don't lose your head。 不要惊慌失措。
182. He can't take a joke. 他开不得玩笑。
183. He owes my uncle $100.他欠我叔叔100美元。
184. How are things going? 事情进展得怎样?
185. How are you recently? 最近怎么样?
186. I know all about it.我知道有关它的一切。
187. It really takes time. 这样太耽误时间了。
188. It's against the law. 这是违法的。
189. Love me,love my dog. (谚语)爱屋及乌。
190. My mouth is watering. 我要流口水了。
191. Speak louder,please. 说话请大声点儿。
192. This boy has no job. 这个男孩没有工作。
193. This house is my own.这所房子是我自己的。
194. What happened to you? 你怎么了?
195. You are just in time. 你来得正是时候。
196. You need to workout. 你需要去运动锻炼一下。
197. Your hand feels cold. 你的手摸起来很冷。。
198. Don't be so childish. 别这么孩子气。
199. Don't trust to chance! 不要碰运气。
200. Fasten your seat belt. 系好你的安全带。
201. He has a large income. 他有很高的收入。
202. He looks very healthy.他看来很健康。
203. He paused for a reply. 他停下来等着?回答。
204. He repaired his house.他修理了他的房子。
205. He suggested a picnic. 他建议搞一次野餐。
206. Here's a gift for you. 这里有个礼物送给你。
207. How much does it cost? 多少钱?
208. I caught the last bus. 我赶上了最后一班车。
209. I could hardly speak.我简直说不出话来。
210. I'll have to try that. 我得试试这么做。
211. I'm very proud of you.我为你感到非常骄傲。
212. It doesn't make sense. 这没有意义(不合常理)。
213. Make yourself at home. 请不要拘礼。
214. My car needs washing. 我的车需要洗一洗。
215. None of your business! 与你无关!
216. Not a sound was heard. 一点声音也没有。
217. That's always the case. 习以为常了。
218. The road divides here. 这条路在这里分岔。
219. Those are watermelons. 那些是西瓜。
220. What a nice day it is! 今天天气真好!
221. What's wrong with you? 你哪里不对劲?
222. You are a chicken. 你是个胆小鬼。
223. A lovely day,isn't it? 好天气,是吗?
224. He is collecting money. 他在筹集资金。
225. He was born in New York. 他出生在纽约。
226. He was not a bit tired. 他一点也不累。
227. I will be more careful.我会小心一些的,
228. I will never forget it. 我会记着的。
229. It is Just what I need. 这正是我所需要的。
230. It rather surprised me. 那事使我颇感惊讶。
231. Just around the comer. 就在附近。
232. Just for entertainment.只是为了消遣一下。
233. Let bygones be bygones. 过去的,就让它过去吧。
234. Mother doesn't make up.妈妈不化妆。
235. Oh,you are kidding me. 哦,你别拿我开玩笑了。
236. She has been to school. 她上学去了。
237. Skating is interesting. 滑冰很有趣。
238. Supper is ready at six. 晚餐六点钟就好了。
239. That's a terrific idea! 真是好主意!
240. What horrible weather! 这鬼天气!
241. Which would you prefer? 你要选哪个?
242. Does she like ice-cream? 她喜欢吃冰淇淋吗?
243. First come first served. 先到先得。
244. Great minds think alike. 英雄所见略同。
245. He has a sense of humor. 他有幽默感。
246. He is acting an old man.他正扮演一个老人。
247. He is looking for a job. 他正在找工作。
248. He doesn't care about me.他并不在乎我。
249. I develop films myself. 我自己冲洗照片。
250. I felt no regret for it. 对这件事我不觉得后悔。
251. I get up at six o'clock.我六点起床。
252. I meet the boss himself. 我见到了老板本人。
253. I owe you for my dinner. 我欠你晚餐的钱。
254. I really enjoyed myself. 我玩得很开心。
255. I'm fed up with my work! 我对工作烦死了!
256. It's no use complaining. 发牢骚没什么用。
257. She's under the weather. 她心情?不好。
258. The child sobbed sadly. 小孩伤心地抽泣着。
259. The rumor had no basis. 那谣言没有?根据。
260. They praised him highly. 他们大大地表扬了他。
261. Winter is a cold season. 冬天是一个,寒冷的季节。
262. You can call me any time. 你可以随时打电话给我。
263. 15 divided by3 equals 5.15除以3等于5。
264. All for one,one for all.我为人人,人人为我。
265. East,west,home is best. 金窝,银窝,不如自己的草窝。
266. He grasped both my hands. 他紧握住我的双手。
267. He is physically mature.他身体己发育成熟。
268. I am so sorry about this. 对此我非常抱歉(遗憾)。
269. I can't afford a new car.我买不起一部新车。
270. I do want to see him now.我现在确实很想去见他。
271. I have the right to know. 我有权知道。
272. I heard some one laughing. 我听见有人在笑。
273. I suppose you dance much. 我想你常常跳舞吧。
274. I walked across the park. 我穿过了公园。
275. I'll just play it by ear. 我到时随机应变。
276. I'm not sure I can do it. 恐怕这事我干不了。
277. I'm not used to drinking. 我不习惯喝酒。
278. Is the cut still painful? 伤口还在痛吗?
279. It's too good to be true! 好得难以置信。
280. Jean is a blue-eyed girl. 珍是个蓝眼睛的女孩。
281. Let's not waste our time. 咱们别浪费时间了。
282. May I ask some questions? 我可以问几个问题吗?
283. Money is not everything.金钱不是一切。
284. Neither of the men spoke. 两个人都没说过话。
285. Stop making such a noise. 别吵了。
286. That makes no difference. 没什么区别。
287. The price is reasonable.价格还算合理。
288. They crowned him king. 他们拥立他为国王。
289. They're in red and white. 他们穿着红白相间的衣服。
290. We all desire happiness. 我们都想要幸福。
291. We just caught the plane 我们刚好赶上了飞机机。
292. What shall we do tonight? 我们今天晚上去干点儿什么呢?
293. What's your goal in life 你的人生目标是什么?
294. When was the house built? 这幢房子是什么时候建造的?
295. Why did you stay at home? 为什么呆在家里?
296. Would you like some help? 需要帮忙吗?
297. You mustn't aim too high 你不可好高骛远。
298. You're really killing me! 真是笑死我了!
299. You've got a point there. 你说得挺有道理的。
300. Being criticized is awful! 被人批评真是痛苦
301. Did you enter the contest? 你参加比赛了吗?
302. Do you accept credit cards? 你们收信用卡吗?
303. Don't cry over spilt milk. 不要做无益的后悔。
304. Don't let chances pass by. 不要让机遇从我们身边溜走。
305. He owned himself defeated.他承认自己失败了。
306. He seems at little nervous. 他显得有点紧张。
307. He strolls about the town. 他在镇上四处遛达。
308. Her tooth ached all night. 她牙疼了一整夜。
309. How about a drink tonight? 今晚喝一杯怎样?
310. I can do nothing but that. 我只会做那件事。
311. I get hold of you at last.我终于找到你了。
312. I have a surprise for you.我有一个意想不到的东西给你看。
313. I like all kinds of fruit.我喜欢各种各样的水果。
314. I saw it with my own eyes.我亲眼所见。
315. I will arrange everything. 我会安排一切的。
316. I wish I knew my neighbor.我很想认识我的邻居。
317. I would like to check out. 我想结帐。
318. It has be come much cooler. 天气变得凉爽多了。
319. It's time you went to bed.你早就该睡觉了。
320. No spitting on the street. 禁止在大街上吐痰。
321. She was totally exhausted. 她累垮了。
322. Show your tickets,please. 请出示你的票。
323. Thank you for your advice. 谢谢你的建议。
324. That's the latest fashion. 这是最流行的款式。
325. The train arrived on time. 火车准时到达。
326. There go the house lights. 剧院的灯光灭了。
327. They are paid by the hour.他们按时取酬。
328. Things are getting better. 情况正在好转。
329. Wake me up at five thirty. 请在五点半叫醒我。
330. We are all busy with work.我们都忙于工作。
331. Where do you want to meet? 你想在哪儿见面?
332. You can get what you want. 你能得到你想要的。
333. A barking dog doesn't bite! 吠犬不咬人。
334. Are you free this Saturday? 你这个星期六有空吗?
335. Be careful not to fall ill.注意不要生病了。
336. Being a mother is not easy. 做一个母亲是不容易的。
337. Brevity is the soul of wit. 简洁是智慧的精华。
338. Cancer is a deadly disease.癌症是一种致命的疾病。
339. Did you fight with others? 你又和别人打架了吗?
340. Don't dream away your time. 不要虚度光阴。
341. Don't keep me waiting long.不要让我等得太久。
342. He has a remarkable memory. 他有惊人的记忆力。
343. He has completed the task. 他完成了这个任务。
344. He has quite a few friends.他有不少的朋友。
345. He is capable of any crime.他什么样的坏事都能干得出来。
346. He walks with a quick pace. 他快步走路。
347. He was not a little tired.他很累。
348. His looks are always funny. 他的样子总是滑稽可笑。
349. How about going to a movie? 去看场电影怎么样?
350. I think I've caught a cold.我想我得了感冒。
351. I was taking care of Sally. 我在照顾萨莉。
352. I wish I lived in NEWYORK. 我希望住在纽约。
353. I'm very glad to hear that.很高兴听你这样说。
354. I'm your lucky fellow then. 我就是你的幸运舞伴啦!
355. It's none of your business! 这不关你的事儿!
356. No littering on the campus.在校园内不准乱丢废物。
357. She is a good-looking girl. 她是一个漂亮女孩。
358. She mended the broken doll. 她修补了破了的洋娃娃。
359. So I just take what I want. 那么我只拿我所需要的东西。
360. Spring is a pretty season, 春天是一个好季节。
361. The figure seems all Right. 数目看起来是对的。
362. The stars are too far away. 星星太遥远了。
363. The whole world knows that. 全世界都知道。
364. Tomorrow will be a holiday. 明天放假。
365. We walk on the garden path.我们走在花园小径上。
366. What you need is just rest. 你需要的就是休息。
367. What's your favorite steps? 你最喜欢跳什么舞?
368. You'd better let her alone.你们最好是让她一个人呆会儿。
369. A lost chance never returns. 错过的机会永不再来。
370. Don't let this get you down. 不要为此灰心丧气。
371. He shot the lion with a gun. 他用枪把狮子打死了。
372. I don't think you are right. 我认为你是不对的。
373. I have never seen the movie. 我从未看过那部电影。
374. I haven't seen you for ages. 我好久没见到你了。
375. I was alone,but not lonely.我独自一人,但并不觉得寂寞。
376. I went there three days ago. 我三天前去过那儿。
377. It's a friendly competition. 这是一场友谊赛。
378. It's very thoughtful of you. 你想得真周到。
379. May I speak to Lora,please? 我能和劳拉说话吗?
380. Mr.Wang is fixing his bike. 王先生在修他的自行车。
381. My brother is see king a job. 我弟弟正在找工作。
382. Nancy will retire next year. 南希明年就退休了。
383. Neither you nor he is wrong. 你没错,他也没错。
384. Opportunity knocks but once. 机不可失,时不再来。
385. She dressed herself hastily. 她匆忙穿上衣服。
386. She hired a car by the hour.她租了一辆按钟点计费的汽车。
387. Someone is ringing the bell. 有人在按门铃。
388. The Smiths are my neighbors. 史密斯一家是我的邻居。
389. These shoes don't fit right. 这双鞋不太合适。
390. This is only the first half. 这才是上半场呢。
391. This pen doesn't write well. 这钢笔不好写。
392. Would you like a cup of tea? 你想喝杯茶吗?
393. You really look sharp today. 你今天真漂亮。
394. Another cat came to my house. 又有一只猫来到我家了。
395. Check your answers with mine.把你的答案跟我的核对一下。
396. Don't keep the truth from me. 别瞒着我事实真相。
397. Everything has its beginning. 凡事都有开端。
398. He came to the point at once.他一下子就说到了点子上。
399. He fell behind with his work. 他工作落后了。
400. He is the happiest man alive. 他是世界上最快乐的人。
401. He neither smokes nor drinks. 他既不抽烟也不喝酒。
402. He ran his horse up the hill. 他策马跑上小山。
403. He reminds me of his brother. 他使我想起了他的弟弟。
404. He was efficient in his work. 他工作效率高。
405. He will do anything but work.只要不是干活,他干什么都行。
406. His father runs a restaurant. 他的父亲经营一家餐馆。
407. I have something to tell you. 我有事要告诉你。
408. I smelled a smell of cooking.我闻到了烧菜做饭的味道。
409. I want to see the film again. 我真想再看一遍。
410. I've got too much work to do. 我要做的工作太多了。
411. Let's go for a walk,shall we? 咱们出去走走,好吗?
412. Please let me check the bill.请让我核对一下帐单。
413. Plenty of sleep is healthful. 充足的睡眠有益于健康。
414. The sun comes up in the east. 太阳从东方升起。
415. This is because we feel pain. 这是因为我们能感到疼痛。
416. What do you desire me to do? 你想要我做什么?
417. What you said was quite true. 你所说的完全符合事实。
418. You can either stay or leave.你或者留下或者离开。
419. Your life is your own affair. 你的生活是你自己的事。
420. All that glitters is not gold. 发闪光的不全是黄金。
421. Are you going to have a party? 你要举行聚会吗?
422. Aren't you concerned about it? 难道你不担心吗?
423. Don't forget to keep in touch. 别忘了保持联系。
424. He broke his words once again. 他又一次违背了诺言。
425. He is in his everyday clothes.他穿着平常的衣服。
426. He is taller than I by ahead. 他比我高一头。
427. He led them down the mountain. 他带他们下山。
428. He was trained to be a lawyer.他被培养成一名律师。
429. I am afraid that l have to go. 我要走了。
430. I don't have any cash with me. 我身上没带现金。
431. I have been putting on weight. 我开始发胖了。
432. I have just finished the book. 我刚刚读完这本书。
433. I was late for work yesterday, 我昨天上班迟到了。
434. It appears to be a true story. 这故事似乎是真的。
435. I've got to start working out. 我必须开始做健身运动了。
436. Japan is to the east of China. 日本在中国的东部。
437. John asked Grace to marry him, 约翰向格雷斯求婚。
438. My watch is faster than yours. 我的表比你的表快。
439. New China was founded in l949. 1949年新中国成立。
440. Thanks for your flattering me.  谢你的夸奖。
441. They charged the fault on him. 他们把过失归咎于他。
442. This car is in good condition. 这车性能很好。
443. This work itself is very easy. 这件工作本身很容易。
444. Truth is the daughter of time. 时间见真理。 
#T=旅游英语
机场英语
1. 托运行李
2. 飞行过程中的英语
3. 在境外转机
4. 抵达目的地，入关
5. 从目的地返回时过安检

1. 托运行李
-  递给对方护照和机票，对方可能会问：
    How many luggages are you checking in? （有多少件托运行李？）
    Do you have a carry on? （有手提行李没？）
    Can you place your baggage up here? （请把行李放上来(传送带/小盒子)）
-  出票前可能会问：
    Do you prefer window or aisle? （想靠窗还是靠走廊）如果对方不问你，但是你想找个靠窗座位，可以说
    Can I have a seat closest to the window?
-  最后，对方给你登机牌，会告诉你登机门号和时间：
    Here are your tickets. The gate number is on the bottom of the ticket.
    They will start boarding 20 minutes before the departure time. You should report to gate C2 by then.
    C2 is around the corner and down the hall. Thank you."
* 如果你行李超重，对方会说 your luggage is overweight. 以上问题回答都是yes, no的就  不写了。
2. 飞行过程中的英语
- 其实没什么好说的，无非是让你选餐时，你选chicken还是beef此类的.....你就说
  Chicken please 一切OK. 如果想要东西时，句型很简单，就是
  Excuse me, Could I have a cup of orange juice, please 这种.

* 如果冷想多要一个毯子可以说 Could I get another blanket, please, I'm a little cold.
* 如果要在飞机上填入境表，没有笔可以说：
  Could you lend me a pen to fill out this immigration form?

* 如果要找个人换座，可以说：Would it be possible to change seats with someone?
* 如果有人坐在你椅子上了，可以说： I'm sorry, I think you are in my seat.
* 机场广播一般.....不用听懂.....空乘可能会提醒你的就是：
  Please fasten your seat belt （请系紧安全带）这类。3. 在境外转机
转机时，先看机票上的航班号，然后从机场的航班指示屏幕上找到该航班在那个GATE登机，最后顺着机场标示走到这个GATE就好，不需要说话。但特殊情况可能是，你到了后，发现屏幕上有你要转的航班号，但是后面的GATE是空的，这时候你可以向机场工作人员确认下 hello, could you tell me which gate is for the flight XXX（航班号） please， 一般他们都会回答这个飞机delay了，或者在maintain , 需要再等待一下。

4. 抵达目的地，入关
其实入关，不用说什么，很多时候你就微笑下，递给海关护照...他盖章就让你进去了，下面是逻辑上可能的标准对话：
海关：where did you fly from? 或者 where have you come from?
你：from China
(如果你不给他护照，或者他需要别的东西会说：
May I have your passport and sth, please?)
海关：what is the purpose of your visit?
你： travel. (如果是探亲，就是 I'm visiting my relatives.)
海关：How long are you planning to stay?
你：Two weeks.
海关：Where will you be staying?
你：I'll be staying at a hotel。
        
5. 从目的地返回时过安检（托运那块和开始是一样的）
- 安检基本上不说话，顶多是查的严时让你脱掉鞋和皮带：
  Take off your belt / Take your shoes off. 什么的

6. 实用单词
姓：Family name，Surname
名：First Name，Given name
性别：sex，gender
男：male； 女：female
国籍：nationality，country of citizenship
护照号：passport number
原住地：country of origin
前往国：destination country
登机城市：city where you boarded
签证签发地：city where visa was issued
签发日期：date of issue
出生日期：date of birth，birth date
年：year；月：month；日：day
偕行人数：accompanying number
签名：signature
官方填写：official use only
职业：occupation
护照：Passport；
签证：Visa
登机、启程：Embarkation
登岸：Disembarkation
商务签证：Business Visa
观光签证：Tourist Visa
乘机常用词汇航站、终点站：Terminal
行李：Baggage，Luggage
托运的行李：Checked baggage
行李领取处：Baggage claim area
随身行李：Carry-on baggage
行李牌：Baggage Tag 
行李推车：Luggage Cart
退税处：Tax-free refund
盥洗室（厕所）：Lavatory，washroom，toiletW.C.＝water closet，rest room
男厕：Men's，Gent's，Gentlemen's
女厕：Women's，Lady's
使用中：Occupied
空闲：Vacant
男（女）空服员：Steward（Stewardess）
机内免税贩卖：In-Flight Sales
钱币兑换常用词汇外币兑换店：Currency Exchange Shop
汇率：Exchange rate
旅行支票：Traveler's check
手续费：Commission
银行买入价：We buy（Bid）
银行卖出价：We sell（Ask）
入境大厅：Arrival Lobby
出境大厅：Departure Lobby
机门号码：Gate Number
登机证：Boarding Card，Boarding Pass
机场税：Airport Tax
登机手续办理处：Check in Counter
海关申报处：Customs Service Area
货币申报：Currency Declaration
免税商品：Duty-Free Items
大号：large；中号：medium；小号：small
纪念品：Souvenir

交通工具

其实不管火车，地铁还是大巴，唯一需要说话的就是买票，所以就不做具体区分了。（话说出行前一定要先研究好线路，或者直接从网上把票定了，这样就没什么麻烦了~） 
你： Hello, Could I get one ticket to London, please (买张到伦敦的票)
(也可以指定时间，再加上 for the 5:00 PM train | 另外买东西时一般就是用Could I have/get，或者I'd like to buy...)
对方：Single or return? (单程往返)
你：Return, please. 
对方：64 Pounds, please. (假设在英国)
你：Here you are. 
对方：Here's your ticket and change.
你：thank you.


* 如果你有优惠卡，比如在英国年轻人可以使用Young Person Card，说第一句话时直接递给他就成，对方会直接告诉你优惠后的价格地。
* 另外，如果你要去london, 但是火车不是直达的，他会告诉你: You have to change trains at Birmingham.(你必须在伯明翰转车) ，如果你自己想问要不要换车，则是Do I have to change trains?
* 如果是火车票的话，对方还可能会告诉你你的train will leave from platform 3(你的火车在几号站台)
* 如果你不确定是不是你要下车的站，可以从旁边抓个人问 Excuse me, I am going to XX , should I get off at this station?


酒店篇
因为大家都是提前在网上预订好，所以这里就不介绍预订英语了，要说话的地方应该就是check in 和check out时，如果想要额外的room service....那进了房间看服务的册子(room menu)吧，这里也不多提了。

Check in 很简单，走进大堂，找到前台，把护照递给他，然后说
         Hi, I have a reservation and I am checking in。

* 他们可能会要你的信用卡，冻结点钱，防止你搞破坏，或者看付费频道后逃跑......
  然后.....他们就给你钥匙......你去找房间就好啦。


Check out 同样，你就说  I am checking out 然后给他们钥匙就成了！

* 如果你有额外消费（收费节目，吃了冰箱的东西等），酒店会对你说：
  "Your credit card will be charged a total of $256.78. Can you sign on the bottom?"
  "Should we charge the credit card on file or did you want to use a different card?"
  然后你签单走人也就好了。
* 如果你不知道几点check out，可以提前一天问前台：
  What time do I have to check out tomorrow?


其他：
* check in后，酒店可能会问你是否need help with your bags，需要的话...记得给小费，不想给就自己来，就说 No thanks 就好。
* 如果你要人给你清扫房间，可以对前台说：Could you get someone to clean my room, please?
* 如果想去别的地方，比如市中心，可以问前台: How do I get to city center from here? Can I take a bus or do I have to take a taxi? 或者 Do you have a map of the city ?
* 如果要前台推荐吃饭的地方可以说: Can you recommend a good restaurant around here?


餐饮篇


快餐，比如麦当劳和Subway，其实...旅游期间...有时候会觉得麦当劳挺好吃的....其英语对话也非常简单：
麦当劳：.... welcome to McDonald's. May I take your order? ...
你： I'll take a Big Mac and a small coke.
麦当劳： One Big Mac and One small coke, Will that be all?
你： Yes
麦当劳： Will that be for here or to go?
你： For here please.
麦当劳： The total comes to 5欧
你：..... 给钱.......
如果你想吃麦香鱼，但是不知道怎么说，或者怎么发音，那其实更简单，你就买套餐！看准了图，然后说： I'll take number 2. 
其他：饮料大小 small , medium, large, super size



餐馆篇
进餐馆时，如果有人招待，可能会问你 Welcome to XX. Do you have a reservation? 你可以说 No, Do you have any free tables right now? ..... 然后他会给你带到桌子那里去，如果你不满意，比如想找个靠窗的桌子，可以说 Could we get a table by the window?

一般你入座后，餐馆先会问你是否要个饮料，比如：
Can I get you a drink? / Would you like to order a drink now? / What would you like to drink.
如果你不想花钱喝饮料，直接说 Water will be fine 或者 Can I have a glass of water? 就成！
想喝东西的话可以说 I'll take a coke, I'll have an orange juice, 或者你可以问下 What kind of drinks do you have?等。


然后餐馆给你端来水（期间你可以研究下菜单），会问你是否开始点菜：
May I take your order? /. What would like to order? / Are you ready to order?

如果你还没想好，说 Can I have a couple more minutes?
想好了...就直接说要点什么就成了：
I'll take the Salisbury steak.... （不会发音， 那就指着菜单说 I'll take this....也成啊）

你点好后，餐馆可能会根据你点的，推荐点别的，比如
Would you like toast, a muffin, or a cornbread?  不想要继续 No thanks 。
...... 然后就可以等着，然后吃饭了！


吃饭期间，有些餐馆可能会来人问你
How is everything? Is everything ok? How is your dinner? Do you need anything else? 
其实...就是问你是否还想要点别的，多赚点钱....话说回来一开始你也确实不用把甜点啊什么都点了... 如果你觉得味道还行可以说 Yes, that was a really great meal. We both loved it. 然后餐馆可能会说 Is there anything else I can get you? 不要就是No thanks，要的话....就继续take这个那个好了。


当你快吃完了，餐馆可能会问你是否来点甜点。
Would you like dessert today?  / Would you like our dessert menu?  
不要的话,no thanks继续，要的话可以要个dessert menu，然后继续take这个那个的。


如果要结账，盯着一个服务人员看，然后挥下手叫人过来，然后说
Can I have my check? 或者 I would like my check please 
(他可能过来会先说 Can I get you anything else?)

* 如果你点的东西半天没人理，可以叫人过来说 I asked for a Coke about 15 minutes ago. 
* 如果你不知道是直接给钱还是收钱的那块给钱(这句话说的很别扭...) 可以拿了check后说 Excuse me, do we pay here or at the case register.
* 如果你不知道餐费里是不是包含了小费，你可以直接问：Is the tip included in the check? 人家说No的话就掏钱吧.....
* 另外...有时候很饿又找不到餐馆，问路时就是 Excuse me, could you tell me where the nearest restaurant is?

最后略微提一下高端餐厅的规矩........我没去过.........传说是点红酒的话，他们会先给你到一点点，然后你要立即喝了，然后说yes，他们才会给你倒满......其他都一样啦，另外这些餐厅通常需要订餐，

购物

一般店员会问：What can I do for you? 或者 Can I help you find something? 
我一般就是 I'm just looking around. 呵呵，如果你确实在找东西，比如要个小号的衬衫，那就是Yes, Do you have this shirt in a smaller size?或者 Where are your blue jeans 这类。
买鞋比较特殊，因为你必须要售货员给拿出来？你要找到店员问:
Can I try this shoe on in a seven?  /  Can I get this in a size six?
因为国内和欧式标准不大一样，所以下面得话比较有用：
I don't know what my size is, can you take my measurement?
在其他类型的店里，其实就不用说什么话了，无非是你在找东西时可以问下，
但句型很简单： Where can I find xxx? / Do you sell XX here?


* 问试衣间在哪里： Where are your fitting rooms?  试过后觉得不合适需要小号，I think I need a smaller size.
* 问是否能刷卡 Can I pay by credit card.
* 确认衣服是不是打折： It's on sale, right?
* 问店什么时候开门，什么时候关门: What time do you open in the morning?  /  What time do you close?
* 最后补一个......最初学者....购物必问句: How much is it?

衣服单词：gloves - 手套,boots - 靴子,socks - 袜子,jeans - 仔裤,jacket - 夹克,skirt - 短裙,hat - 帽子,shoes - 鞋,belt - 皮带,shirt - 衬衫 ,boxers - 男士短裤

其他（换钱，问路等..... 继续补充中）
换钱会用到：
Do you exchange foreign currency?  /  Can I cash my traveler's checks here?
What is your exchange rate for the Chinese yuan?
The exchange rate is 0.0009 cents for one yuan.
I would like to exchange 500 yuan please.


问路 --- 其实问了后，特麻烦的很多好心人会带着你走，特复杂的，你没听懂的话....也没关系.....有个大概方向，然后一路问下去就好了，呵呵。
Excuse me, Do you know where the post office is?
Excuse me, I am looking for the post office, do you know how to get there?
可能回答（有很多种，随便挑了几个）
Turn right after you pass McDonalds.
When you see a church on your left hand side, turn right on the next street.
Go down the street, turn left on Williams street, and it will be right around the corner from the gas station.
It's pretty far from here, Go on Williams Street for about 2 miles, you'll see it next to a school.


补充些单词：

半日列岛游（island hopping half day）
全天列岛游（island hopping full day）
落日海豚之旅（sunset dolphin cruise）
马累购物游（male’s shopping ferry/discover male）
水上飞机摄影（photo flight by seaplane）
黄昏海钓 (sunset fishing)
夜晚海钓 (night fishing)
浅滩浮潜 (sand bank snorkelling)

潜水设备租赁 Diving equipment Leasing
潜水装备  DIVE EQUIPMENT OR GEAR  
面镜  MASK  
近视镜片  OPTICAL LENS  
游泳镜  GOGGLE  
防雾剂  ANTI-FOG SPRAY  
蛙鞋  FINS  
面镜带  MASK STRAP  
呼吸管  SNORKEL  
扣环  BUCKLE  BC    
套式蛙鞋  SHOES FIN  
湿式防寒衣  WET SUIT  
干式防寒衣  DRY SUIT  
水母衣  DIVE SKIN  
潜水背心  VEST  
防滑鞋  BOOTS  
脚底  SOLES  
手套  GLOVE  
止滑  NON-SLIP  
咬嘴  MOUTH PIECES  
浮潜救生衣  SNORKELING VEST  
潜水刀  KNIFE  
背包  BACK PACK  
潜水手电筒  DIVE LIGHT  
备用气瓶  SPARE AIR TANK (PONY BOTTLE)  
硅胶面镜  SILICONE MASK  
黑胶面镜  RUBBER MASK  
哨子  WHISTLE  
空气枪  AIR GUN  
水中写字板  PLATE  
防水盒  HOUSING  
相机硬壳行李箱  PHOTO CASE  
数字相机  DIGITAL CAMERA  
潜水帽  HOOD


《旅游英语口语-应急版》那篇文章写的比较早，比较通用，比较适合欧美城市旅游，大家在海岛游的时候英语困惑其实不大多(毕竟主要项目是去海边玩水，不是乘车去逛博物馆：)  后来发现新人的困惑主要是餐馆英语，所以在此整理下。


本文分为这么几个部分：
1. 餐馆的基本对话
2. 常用菜单词汇
3. 以普吉岛lotus餐厅为例，将其网站上的菜单进行翻译 - 主要是演示下其实很容易。

× 本文内容枯燥无趣...建议还是打印下来，在飞机上翻看：） 另外，本文作者水平不高，难免有英文和餐饮上的错误，大家发现请指正，有新信息请补充：）
× 文章更新充实中，大家外出时方便的话不如拍摄下菜单然后跟贴到这里：）



1. 餐馆的基本对话

首先要说的是，不需要多复杂的英语，说关键词，听关键词就成，对方普遍有口音，你想听完整其实也费尽，如果你说长句子，对方也不明白：） 简单，保持简单～ 下面的例子都是完整版了，记忆个大概齐说就成啦。

进入餐馆/点餐时：
May we sit at this table? 请问我们可不可以坐这桌
Do you have the menu in Chinse/with Photo,please? 
请问有没有中文菜单，或者带照片的菜单，注意要说那个please哈
I'd like the....,please。
我想点....读菜单，或者直接指文字说I‘d like this one 

× 如果对方问Are you ready to order yet? 你还要纠结的话，说Could you give us a couple more minutes?
× 订餐后如没有点饮料对方可能问Would you like someting to drink? 你说No,thanks或者Yes,I'd like a coke什么的就行
× 如果要预订，那说I'd like to book a table for four(4个人) at 7pm（7点）,please.
× 如果要砍价(海鲜大排档)，那点菜后对方会告诉你总价，然后你说expensive，在他给的计算器上输入新价格就OK啦～

用餐时：
Could you bring me the XX（比如ketchup 番茄酱，自由替换）,please？ 可以给我下番茄酱吗？
Excuse me, we've been waiting for over half an hour.  我们已经等了半个多小时啦
I'll have the same. 好吧，懒得点不知道怎么点的时候的万能句
Please bring us another beer, please(Another beer, pease)  多点什么的时候用another就可以搞定

付款时：
Could I have the bill,please?  付账，谢谢。 给账单时对方也会报价 That'll be $50.
Do you accept credit card?  你们是否可以刷卡？
This is on me 我请客



2. 常用菜单词汇

常见的菜单栏目分类：
这个是首先要看的，看懂这个了就不会点错了：）

Appetizers 前菜/开胃菜，有时候也叫Finger Food/Snacks/Starters
Salads (and Soups) 沙拉/汤，有时候也较Garden Fresh或者Low-fat Selections等
Sandwiches 三明治，不解释了...我很喜欢。
Italian 意式菜，比如Pasta,Spaghetti(面条状的那种意大利面),Pizza，如果进了家餐馆发现东西贵，或者觉得不值时，点个Pizza就好，在大多数餐厅都是物美价廉，可以让人吃饱的选择！
Main Course 主菜，也叫Entrée，Main Dish，比如牛排Steak这类都是叫主菜。
Sides 附菜，比如说薯条Frech Fries
Seafood 海鲜啦，大家想吃海鲜大排档等等时，就盯着大照片上有没有Seafood这个大字哈！普通餐厅里的seafood有时候指的是smoked salmon(熏三文鱼)这种，没有大家想像中的lobster,crab这些。
Mexican 墨西哥菜式..这个不懂了，不乱说。
Specialties 特色菜系，每家餐厅的拿手菜，价格合适的话，可以点一个尝尝的！
Desserts 甜品，也叫Sweets，比如cheesecake(这个很好很好)，apple pie这些。
Beverages 非酒精类饮品，也叫Drinks, 比如Coke,Milk,各种Juice啦。
Wine and Beer 酒精类饮品，这里面的种类就太多，随意点吧。




关于做法的词汇：
boiled: 煮的
steamed：蒸的
fried：炸的
stir-fried: 炒的
roasted：烤的(在烤箱里烤)
baked：烤的(在烤箱里，和上面的区别是，roasted用来形容烤之前就有形状的食品，比如鸡肉，baked用来形容会变化的，比如面包)
grilled：烤的(在烤架上烤)
somked: 烟熏的



常见食品形容词：
crispy：脆的
fresh：新鲜的
juicy：多汁的
creamy: 奶油的
spicy: 辛辣的
Jumbo: 大个的
chunky: 块状的，形容蔬菜或者肉
seasonal: 时蔬的“时”字，就是根据季节而选择的材料，菜单上不印出，比如seasonal fruit。
home style/homemade：厨师自制的，而不是买的，一般形容一些调料是厨师自己做的，新鲜什么的～

常见食物名称：
meat: 红肉, 常见的是猪肉(pork) 牛肉(beef) 羊肉(lamb)
cold meat: 冷肉，比如培根(bacon) 火腿(ham) 腊肠(salami)
poultry: 家禽类，比如鸡(chicken) 火鸡(turkey) 鹅(goose) 鸭(duck)
game: 野味, 比如家兔(rabbit) 野兔(hare) 松鸡(partridge) 野鸡(pheasant) 
fish: 鱼类，比如石斑鱼(grouper) 金枪鱼(tuna) 三文鱼(salmon) 鳕鱼(cod) 鳟鱼(trout) 
seafood：海鲜，比如对虾(prawn) 小虾(shrimp) 龙虾(lobster) 扇贝(scallops) 青口(mussels) 螃蟹(crab) 鱿鱼(squid) 章鱼(octopus) 生蚝(oyster)  蛤蜊(clam) 
vegetables: 蔬菜，比如洋葱(onion) 黄瓜(cucumber) 西红柿(tomato) 玉米(corn)
fruit: 水果，比如木瓜(papaya) 火龙果(pitaya) 菠萝(pineapple) 榴莲(durian) 山竹(mangosteen) 芒果(mango) 西瓜(watermelon) 
soup: 汤
salad: 沙拉
主食：意大利通心粉(pasta) 意大利细面条(spaghetti) 比萨(pizza) 米饭(rice) 面包(bread) 面条(noodle)
佐料：糖(sugar) 盐(salt) 辣椒(pepper) 蒜(garlic) 黄油(butter)




3.  最后以一个真实菜单为例 -选择普吉岛Lotus海鲜餐厅：

Lotus的菜单分类是：
Appetizer 开胃菜
Thai Salad 泰式沙拉
European Food 欧式食物
Tiger Prawn & Prawns 大虾
Lobster 龙虾
Crab & Shell Fish 螃蟹和贝类
Fish 鱼

【Appetizer 】
Shrimp Cake 虾肉糕(不过我想翻译成虾饼更合适，吃过的同学请提示～)
Fish Cake 鱼肉糕
Spring Rolls(with prawns) 虾馅春卷
Chicken in Pandanus Leaves 露兜树叶鸡肉
Koong Sarong 不知道如何翻译，请google这个词的图片，很不好形容这东西
Kai Jor (Chicken Cake) 鸡肉糕
Chicken/Pork Satay 鸡肉/猪肉串
Steam Fish Ball 蒸鱼球
Deep Fried Prawns 炒虾
Deep Fried Squid  炒墨鱼
Mixed Appetizer(for 2-3 person) 小吃品牌 2-3人用，下面是都含有什么
Shrimp cake, Vegetable Spring Rolls, Chicken Satay, Onion Ring and Green Mango Salad

【Thai Salad】
* 注意，泰式沙拉都是辣的....
Spicy Prawns Salad(With shallots, onion, tomato) 辣虾肉沙拉(配以青葱，洋葱，西红柿)
Spicy Seafood Salad(With shallots, onion, tomato) 辣海鲜沙拉 - 估计里面就是多了虾和蟹肉
Laab Moo/Laap Kai(Minced pork/chicken salad with shalot, spring onion) 碎猪肉/鸡肉沙拉
Spicy B.B.Q. Beef Salad 辣BBQ味牛肉沙拉
Green Papaya/Mango Salad 青木瓜/芒果沙拉
Pomelo Salad with Prawns  柚子虾肉沙拉
Yam Sam Grob (Dried seafood salad) 没吃过，感觉是把海鲜炸过了做的沙拉
Glass Noodle Salad With seafood 这个glass noodle貌似就是粉丝，呵呵

【European Food】
Mixed Salad 什锦沙拉
Green Salad 青菜沙拉
Tuna Salad 金枪鱼沙拉
Crab Meat Salad 蟹肉沙拉
Ceasar Salad 凯撒沙拉
Grilled Salmon Salad 烤三文鱼沙拉
Grilled Chicken Salad 烤鸡肉沙拉
Club Sandwich 三明治 - 很经典的那种有点蔬菜，火腿，西红柿的那种
Grilled Ham Cheese Sandwich 烤火腿芝士三明治
Tuna Sandwich 金枪鱼三明治
Hamburger/ With Cheese(Serve with French fried) 汉堡+薯条 
Fish & Chip （英式）鱼和薯条
Spaghetti With seafood or bolognas sauce 海鲜/腊肠意大利细面条
Grilled Pork Chop 烤猪肉
Grilled Strip Loin Steak(Pepper sauce served with mixed vegetable and French fried) 烤牛排+辣椒酱+蔬菜什锦+薯条
Salmon Steak Serve with mixed vegetable and French fried 烤三文鱼，配以蔬菜，薯条
Grilled Chicken Breast Served with mixed vegetable and French fried 烤鸡胸，配以蔬菜，薯条
French Fried 薯条
Chicken Finger 炸鸡肉条

【Prawns & Tiger Prawn】
B.B.Q.Tiger Prawns With garlic and butter sauce做法的老虎虾，陪蒜味+黄油酱汁(其实也不知道翻译，大家google下图片吧)
Tiger Prawns with Panang Curry Panang咖喱味老虎虾
Fried Tiger Prawn with Garlic 蒜味炒老虎虾
Steamed Tiger Prawn With garlic sauce 蒸老虎虾配蒜酱
Steamed Tiger Prawn with Timarind Sauce 蒸老虎配Timarind?酱
B.B.Q. White Prawn 这里开始就是说的是白虾了
Steamed White Prawns with Garlic & Butter 蒸
Fried White Prawns with Garlic 炒
Fried Prawns with Red Curry 炒，咖喱味
Fried Prawns with Cashew Nuts 炒，配腰果
Fried Prawns with Timarind Sauce 又是那种奇怪酱
Prawns with Sweet & Sour Sauce 这个是配甜酸酱
Prawns with Green Curry 配绿咖喱
Fried Prawns with Green Bean & Shrimp Paste 配青豆和小虾酱

【Lobster】
B.B.Q.Lobster Served with Garlic Sauce  BBQ味龙虾配蒜味酱
Steamed Lobster Served with garlic sauce & garlic butter sauce  蒸
Loster Tormido(Lobster baked with cheese) 所谓奶油芝士焗龙虾
Lobster with Black Pepper 黑胡椒龙虾
Lobster with Panang Curry Panang咖喱味龙虾
Lobster Sashimi(Served with vasabi and Kikkoman sauce) 龙虾刺身
Fried Mantis Shrimp with Salt, Garlic & Chilli 炒皮皮虾(螳螂虾)
Steamed Mantis Shrimps 蒸皮皮虾 
B.B.Q. Mantis Shrimps BBQ味皮皮虾

【CRABS & SHELL FISH】
Steamed Crab  蒸螃蟹
Fried Crab with Curry Powder 炒咖喱蟹
Crab with Black Pepper 黑胡椒蟹
Chili Crab 辣椒蟹
Fried Crab with Ginger 姜味蟹
Crab with Red Curry 红咖喱味蟹
Spicy Fried Crab with Lime Sauce 辛辣蟹配柠檬酱
Steamed Crab with Glass Nooddle 粉丝蒸螃蟹
Soft Shell Crab with Black Pepper 黑胡椒软壳蟹(蟹类的一种)
Fried Soft Shell Crab with Garlic 蒜味炸软壳蟹
B.B.Q. Squid BBQ味鱿鱼
Fried Squid with Garlic 蒜味炒鱿鱼
Fried Squid with Chili Paste 辣椒酱炒鱿鱼
Oyster Raw/B.B.Q. 生/BBQ味道生蚝
Oyster Omellete (With black Pepper served in a hot pan) 这个Omellete是一种鸡蛋饼状物，大家google吧）
Garlic Oysters 蒜味生蚝
Mussel Omellete(With black Pepper served in a hot pan) 青口Omellete
Steamed Mussel with Herbs 药草蒸青口
Garlic Mussel 蒜味青口
Fried Mussel with Chilli Paste 辣椒酱炸青口
Steamed/ B.B.Q. Clam 蒸/BBQ蛤蜊
Fried Clam with Garlic and Chilli 辣蒜炒蛤蜊
Baked Mussel with Tomato Sauce 番茄酱烤青口


【FISH】
B.B.Q Fish  BBQ味鱼
Fried Fish with Garlic 蒜味炸鱼
Steamed Fish with Ginger（With spring onion and soya sauce）姜蒸鱼,配青葱，酱油
Steamed Fish with Lime Sauce 柠檬汁蒸鱼
Pla Sam Rod （Fried fish with sweet chili sauce）甜辣酱煎鱼
Fried fish in tomato sauce and vegetable 番茄酱蔬菜炸鱼
#T=出国实用英语(1)
1.机场英语
2.病情
3.熟练口语
4.家居日用品
5.食品
6.中国特色
7.必知缩写
8.必备成语
9.女生用品
1.机场英语
机场指示牌 airport signs 
机场费airport fee  
国际机场 international airport  
国内机场 domestic airport  
国际候机楼 international terminal  
国际航班出港 international departure  
国内航班出站 domestic departure  
入口 entrance 
出口 exit; out; way out  
进站（进港、到达） arrivals  
不需报关 nothing to declare  
海关 customs  
登机口 gate; departure gate  
候机室 departure lounge  
航班号 FLT No (flight number)  
来自…… arriving from  
预计时间 scheduled time (SCHED)  
实际时间 actual  
已降落 landed  
前往 departure to  
起飞时间 departure time  
延误 delayed  
登机 boarding  
由此乘电梯前往登机 stairs and lifts to departures  
迎宾处 greeting arriving  
由此上楼 up; upstairs  
由此下楼 down; downstairs  
货币兑换处 money exchange; currency exchange  
订旅馆 hotel reservation  
行李暂存箱 luggage locker  
出站（出站、离开）departures  
登机手续办理 check-in  
登机牌 boarding pass (card)  
护照检查处passport control immigration  
行李领取处 luggage claim; baggage claim  
国际航班旅客 international passengers  
中转旅客 transfer passengers  
中转处 transfer correspondence  
过境 transit  
报关物品 goods to declare  
贵宾室 V.I.P. room  
购票处 ticket office  
付款处 cash  
出租车乘车点 Taxipick-up point  
大轿车乘车点 coachpick-up opint  
航空公司汽车服务处 airline coach service  
租车处（旅客自己驾车） car hire  
男厕 men’s; gent’s; gentlemen’s  
女厕 women’s; lady’s 
厕所 toilet 
免税店 duty-free shop  
邮局 post office  
出售火车售 rail ticket  
旅行安排 tour arrangement  
行李暂存箱 luggage locker  
行李牌 luggage tag  
机票 air ticket 
旅客姓名 name of passenger  
旅行经停地点 good for passenger between  
订座情况 status  
机票确认 ticket confirm  
承运人（公司） carrier  
座舱等级 class(fare basis)  
机号 plane No.  
机座号 seat No.  
非吸烟席 non-smoking seat  
姓 family name / surname 
名 First Name / Given Name  
国籍 nationality  
护照号 passport No.  
原住地 country of Origin (Country where you live)  
前往目的地国 destination country  
登机城市 city where you boarded  
签证签发地 city where visa was issued  
签发日期 date issue  
街道及门牌号 number and street  
城市及国家 city and state  
出生日期 date of Birth (Birthdate)  
偕行人数 accompanying number  
职业 occupation  
专业技术人员 professionals & technical  
行政管理人员 legislators &administrators  
办事员 clerk  
商业人员 commerce (Business People)  
服务人员 service  
签名 signature  
官方填写 official use only  
签证 visa 
出生日期 birthdate  
护照号 passport No.  
编号 control No.  
签发地 Issue At  
签发日期 Issue Date（或On）  
签证种类 visa type (class) 
浦东机场 Pudong Airport 
虹桥机场 Hongqiao Airport 
磁悬浮 maglev 
地铁 subway / metro
机场巴士 airport bus 
商务中心 business center 
国际、港澳台登机 International & Hongkong-Macau-Taiwan Boarding 
国内登机 domestic boarding 
航站楼 Terminal 
长途汽车 Long distance bus 
停车库 Parking lot 
酒店班车 shuttle bus for hotels 
汇合点 meeting point 
向上自动扶梯 escalator up 
向下自动扶梯 escalator down 
无障碍洗手间 facilities for disabled person 
行李寄存 baggage deposit 
失物招领 lost and found
2．病情
(1) 一般病情: 
He feels headache, nausea and vomiting. (他觉得头痛、恶心和想吐。)  
He is under the weather. (他不舒服，生病了。)  
He began to feel unusually tired. (他感到反常的疲倦。)  
He feels light-headed. (他觉得头晕。)  
She has been shut-in for a few days. (她生病在家几天了。)  
Her head is pounding. (她头痛。)  
His symptoms include loss of appetite, weight loss, excessive fatigue, fever and chills. (他的症状包括没有食欲、体重减轻、非常疲倦、发烧和发冷。)  
He feels exhausted or fatigued most of the time. (他大部份时间都觉得非常疲倦。)  
He has been lacking in energy for some time. (他感到虚弱有段时间了。)   
He feels drowsy, dizzy and nauseated. (他觉得昏昏欲睡，头晕目眩和想吐。)  
He feels as though everything around him is spinning. (他感到周围的东西都在打转。)  
He has noticed some loss of hearing. (他发觉听力差些。)  
She has some pains and itching around her eyes. (她眼睛四周又痛又痒。) 

(2) 伤风感冒：
He has been coughing up rusty or greenish-yellow phlegm. (他咳嗽带有绿黄色的痰。)  
His eyes feel itchy and he has been sneezing. (他眼睛发痒，而且一直在打喷嚏。) 
He has a fever, aching muscles and hacking cough. (hacking = constant) (他有发烧，筋骨酸痛和常常咳嗽。)  
He coughed with sputum and feeling of malaise. (malaise = debility) (他咳嗽有浓痰，而且觉得很虚弱。) 
He gets a cold with a deep hacking cough. (他伤风咳嗽。)  
He has a headache, aching bones and joints. (他头痛，骨头、关节也痛。)  
He has a persistent cough. (他不停地在咳。)  
He has bouts of uncontrollable coughing. (他一阵阵的咳嗽，难以控制。) 
He has hoarse and has lost his voice sometimes. (他声音嘶哑，有时失声。)  
He has a sore throat and a stuffy nose. (他嗓子疼痛而且鼻子不通。)  
His breathing is harsh and wheezy. (他呼吸时，有气喘似的呼哧呼哧作响。) 
He has a stabbing pain that comes on suddenly in one or both temples. (有时突然间太阳穴刺痛。)  
He has a runny nose, sneezing or a scratchy throat. (他流鼻水，打喷嚏和喉咙沙哑。) 

(3) 女性疾病：
She has noticed one lump in her breast. (她发觉乳房有个肿块。) 
There is a hard, swollen lump on her right breast. (她右乳房有肿块。)  
Her left breast is painful and swollen. (她左乳房疼痛且肿大。)  
She has heavy bleeding with her periods. (她月经来的很多。)  
Her vaginal discharge is white or greenish-yellow and unpleasant smelling. (她阴道分泌物带白色或绿黄色，而且气味不好。)  
She has noticed occasional spotting of blood between periods. (在月经来的前后，她有时也发觉有滴滴达达的流血。)  
She has some bleeding after intercourse. (性交后有出血。)  
She feels some vaginal itching. (她感到阴部发痒。)  
She has painful periods and abnormal vaginal discharge. (她月经来时疼痛，而且阴道有不正常的分泌物。) 

(4) 手脚疾病： 
His both hands and feet ache all over. (他两手两脚都很酸痛。)  
He has pain on the sole of his feet. (他脚底很痛。) 
There is a wart-like lump on the sole of right foot. (我右脚底有个像肉疣般的硬块。) 
His ankles look puffy and they pit when he presses them with his finger.  (pit = small dent form；句里的 they 和 them 都是指 ankles)(他的足踝好象肿了，用手按，就有小坑痕。)  
The pain in his left foot is accompanied by redness and swelling. (左脚酸痛，并有红肿。)  
The joints near his fingernails and knuckles look swollen. (指头和指节旁边的关节，似乎有肿大。)  
He has numbness and tingling in his hands and fingers. (他的手和指头感到麻木和刺痛。)  
His legs become painful following strenuous exercise. (激烈运动后，他的腿就痛。) 
His knee is misshapen or unable to move. (他的膝盖有点畸形，也不能动。) 
There are some swellings in his armpit. (他的腋窝肿大。)  
He is troubled with painful muscles and joints. (他的筋骨和关节都痛。)  
She is troubled by the pains in the back and shoulders. (她的后背和肩膀都痛。)  
His knee has been bothering him for some time. (他的膝盖不舒服，已有一段时间了。) 

(5) 睡眠不好：
He is sleeping poorly.（他睡不好） 
He has difficulty in sleeping, inability to concentrate.（他不易入睡，也难集中精神。）  
It is usually hard for her to fall asleep when she goes to bed at night.（她晚上就寝，很难入睡。） 
He wakes during the night or early morning and finds it difficult to fall asleep again.（他晚间或清早醒来后，再也不能入睡。）  
He has nightmares occasionally.（他有时做噩梦。）  

(6) 男性疾病： 
He urinates more frequently than usual.（他小便比平时多。）  
He has difficulty controlling his bladder.（他很难控制小便。）(bladder：膀胱)  
There are some lumps on his testicles. （他的睪丸有些硬块。） 
He has had burning or pain when he urinates.（他小便时感到发烫和疼痛。）  
He is passing less urine than usual.（他小便比平时少。） 
He has had painless swelling in his scrotum.（他的阴囊有不痛的肿大。）  
He feels lack of interest in sex.（他自觉对性的兴趣大减。）  
He has difficulty starting his urine flow.（他小便不畅通。） 
His urine stream is very weak and slow.（他小便流动得很慢很弱。） 
He dribbles a little urine after he has finished urinating.（他小便后，还会有少量零星地滴下。） 
He has had some discharge from his penis.（他的阴茎排出一些流脓。）  
His urine is cloudy and it smells strong.（他的小便混浊，而且气味不好。）  
He has a dull heavy ache in the crotch.（他的胯部感到隐痛。）  
He has a small leakage of urine when he coughs or sneezes.（他咳嗽或打喷嚏时，会有点泄尿。）  
He has trouble urinating.（他小便有困难。） 

(7) 呼吸方面：
His breathing has become increasingly difficult.（他呼吸越来越困难。） 
He has to breathe through his mouth.（他要用口呼吸。） 
He is short of breath, even when he has not been exercising, he is breathless.（他喘气；即使不运动，他也是上气不接下气。） 
His cough is more like wheezing.（他的咳嗽有呼哧呼哧的响声。）  
His cough is dry, producing no phlegm.（他是干咳，没有痰。）  
He has coughed up blood.（他咳嗽有血。）  
His nose stuffed up when he had a cold.（他感冒时鼻子就不通。）  
He coughs up a lot of phlegm (thick spit) on most days.（他多半时间咳出浓浓的痰。） 
He has a feeling of tightness in the chest or a feeling that he is suffocating.（他胸部觉得闷闷的，好象透不过气来。） 

(8)口腔毛病： 
He has pain in his teeth or jaw. (他的牙齿和下巴疼痛。) 
He has some problems with his teeth. (他牙齿有问题。)  
The tooth hurts only when he bites down on it. (他咬东西时，牙齿就痛。)  
His gums are red and swollen. (他的牙床红肿。) 
His tongue is red and sore all over. (他的舌头到处红和痛。) 
His breath smells bad and he has a foul taste in his mouth. (他口里有怪味。)  
His gums do bleed. (他牙床有出血。)  
He has some sore swellings on his gum or jaw. (他的牙床和下巴肿痛。)  
He has sore places on or around the lip. (他的嘴唇和周围都很痛。)  
There are cracks at the corners of his mouth. (他的嘴巴角落破了。)  
There are some discolored areas inside on his tongue. (他舌头里边有些地方颜色怪怪的。)  

(9) 肠胃毛病：
He has a bloated, uncomfortable feeling after meal. (他饭后肚子觉得胀胀的，很不舒服。) 
He has bouts of abdominal pain. (他有一阵阵的肚痛。)  
He feels bloated in his abdominal area. (他感到肚子胀胀的。) (注：胀胀的，像「puff up」，但不是真正的肿「swell up」。)  
The pain is mainly in the lower (upper) right part of the abdomen. (痛是在肚子下半部。)  
He has nausea and vomiting. (他有恶心和呕吐。)  
It is difficult or painful for him to swallow. (他吞下食物时会痛。)  
He has passed more gas than usual. (他放…比平常多。) 
He has been constipated for a few days. (他便秘了好几天。) 
He suffers pains when he moves his bowels. (他大便时很痛。)  
He has some bleeding from his rectum. (他的肛门出血。)  
He has noticed some blood in his bowel movements. (他发觉大便时有些血。)  
His bowel movements are pale, greasy and foul smelling. (他大便呈灰白色，含油脂的恶臭。)  
His bowel movements are grey (or black) in color. (他的大便呈灰白色。)  
He has trouble with diarrhea. (他拉肚子。) 

(10) 血压&感官： 
His blood pressure is really up. (他的血压很高。)  
High blood pressure is creeping up on him. 
He has noticed frequent urination, increased thirst and unexpected tireness. (他发觉常常小便，非常口渴和更加疲倦。)  
It is a chest pain that gets worse when he bends over or lies down. (他弯腰或躺下时，胸部更痛。)  
He has noticed excessive sweating and unexplained tireness. (他体会到过度的出汗和难以解释的疲倦。)  
He has a sharp pain in one area of his spine. (他的脊椎某部位刺痛。)  
He has pain in other joints including hip, knee and ankle. (其它关节疼痛包括臀部、膝盖和脚踝。)  
His eyes seem to be bulging. (他的眼睛觉得有点肿胀。)  
He has double vision. (他的视线有双重影子。) 
He feels there is a film over his eyes. (他觉得眼里有种薄膜似的东西，挡住视线。) 
His vision in the right eye blurred. (他右眼视线模糊不清。)  
He has had some earaches lately. (他近来耳朵有点痛。) 
He has a repeated buzzing or other noises in his ears. (他耳朵常有嗡嗡的声音。) 
3．熟练口语
Any day will do？哪一天都可以？ 
Any messages for me？有我的留言吗？ 
Are you by yourself？你一个人来吗？ 
All right with you？你没有问题吧？ 
　　Are you free tomorrow？明天有空吗？ 
　　Are you kidding me？你在跟我开玩笑吧？ 
　　As soon as possible！尽可能快！ 
　　Back in a moment！马上回来！ 
　　Believe it or not！信不信由你！ 
　　Better luck next time！下次会更好！ 
　　Boy will be boys本性难移！ 
　　Come to the point！有话直说！ 
　　Do you accept plastic？收不收行用卡？ 
　　Does it keep long？可以保存吗？ 
　　Don't be so fussy！别挑剔了！ 
　　Don't count to me！别指望我！ 
　　Don't fall for it！不要上当！ 
　　Don't get me wrong！你搞错了！ 
　　Don't give me that！少来这套！ 
　　Don't let me down！别让我失望！ 
　　Don't lose your head！别乐昏了头！ 
　　Don't over do it！别做过头了！ 
　　Don't sit there daydreaming！别闲着做白日梦！ 
　　Don't stand on ceremony！别太拘束！ 
　　Drop me a line！要写信给我！ 
　　Easy come easy go！来得容易去得也快！ 
　　First come first served！先到先得！ 
　　Get a move on！快点吧！ 
　　Get off my back！不要嘲笑我！ 
　　Give him the works！给他点教训！ 
　　Give me a break！饶了我吧！ 
　　Give me a hand！帮我一个忙！ 
　　Great minds think alike！英雄所见略同！ 
　　I'll treat you to lunch.午餐我请你！ 
　　In one ear，out the other ear.一耳进，一耳出！ 
　　I'm spaced-out！我开小差了！ 
　　I beg your pardon！请你再说一遍！ 
　　I can't afford that！我付不起！ 
　　I can't follow you！我不懂你说的！ 
　　I can't help it！我情不自禁！ 
　　I couldn't reach him！我联络不上他！ 
　　I cross my heart！我发誓是真的！ 
     I don't mean it！我不是故意的！ 
　　I feel very miserable！我好沮丧！ 
　　I have no choice！我别无选择了！ 
　　I watch my money！视财如命！ 
　　I'll be in touch！保持联络！ 
　　I'll check it out！我去看看！ 
　　I'll show you around！我带你四处逛逛！ 
　　I'll see to it！我会留意的！ 
　　I'm crazy for you！我为你疯狂！ 
　　You make me jump！你下了我一跳！ 
　　Make up your mind.作个决定吧！ 
　　Make yourself at home！就当在家一样！ 
　　My mouth is watering！我要流口水了！ 
　　Never heard of it！没听说过！ 
　　Nice talking to you！很高兴和你聊天！ 
　　No doubt about it！勿庸置疑！ 
　　No pain no gain！不经一事，不长一智！ 
　　None of your business！要你管？ 
　　There is nothing on your business！这没你的事！ 
　　Now you are really talking！说得对！ 
　　Please don't rush me！请不要吹促我！ 
　　Please keep me informed！请一定要通知我！ 
　　She looks blue today.她今天很忧郁！ 
　　She is under the weather.她心情不好！ 
　　So far，so good.过得去。 
　　Speaking of the devil！一说曹操，曹操就到！ 
　　Stay away from me！离我远一点！ 
　　Stay on the ball！集中注意力！ 
　　That makes no difference.不都一样吗？ 
　　That's a touchy issue！这是个辣手得问题！ 
　　That's always the case！习以为常！ 
　　That's going too far！这太离谱了！ 
　　That's more like that！这才象话嘛！ 
　　The answer is zero！白忙了！ 
　　The dice is cast！已成定局了！ 
　　The same as usual！一如既往！ 
　　The walls have ears！隔墙有耳！ 
　　There you go again！你又来了！ 
　　Time is running out！没有时间了！ 
　　We better get going！最好马上就走！ 
 
Absence makes the heart grow fonder. 小别胜新婚。 
After you． 您先。  
Allow me． 让我来。  
Any day will do． 哪一天都行夕  
Any messages for me? 有我的留言吗?  
Any thing else? 还要别的吗?  
Any urgent thing？ 有急事吗？ 
Are you kidding? 你在开玩笑吧!  
Are you sure? 你肯定吗?  
As soon as possible! 越快越好!  
Be careful! 注意!  
Be quiet! 安静点!  
Believe it or not! 信不信由你!  
Between us. 你知，我知。  
Big mouth! 多嘴驴！  
Blast! **！ 
Bless you! 祝福你!  
Bottle it! 閉嘴！ 
Bottoms up! 干杯！ 
Bottoms up! 干杯(见底)!  
Boy! （表示惊奇，兴奋等）哇！好家伙！ 
Break the rules. ?#;反規則。 
Break the rules. 违反规则。 
Can I have this. 可以给我这个吗？ 
Can I help you? 我能帮你吗?  
Can you dig it？ 你搞明白了吗？ 
Can－do. 能人。 
Cheap skate! 小气鬼！ 
Cheer up! 振作起来!  
Chin up. 不气 ，振作些。 
Close－up. 特寫鏡頭。 
Clothes make the man． 人要衣装。  
Come on! 快点，振作起来！  
Come on, be reasonable. 嗨，你怎么不讲道理。 
Come on． 来吧(赶快)  
Come seat here. 来这边坐。 
Congratulations! 祝贺你!  
Control yourself! 克制一下!  
Count me on 算上我。  
Daring! 亲爱的！ 
Dead end. 死胡同。 
December heartbeat. 黄昏恋。 
Did you miss the bus? 你错过公共汽车了?  
Dinner is on me. 晚饭我请。 
Do l have to 非做不可吗?  
Do me a favor? 帮个忙，好吗?  
Do you have any money on you？ 你身上带钱了吗？ 
Do you have straw？ 你有吸管吗？ 
Does it serve your purpose？ 对你有用吗？  
Doggy bag. 打包袋。 
Don't be so childish. 别这么孩子气。  
Don't be so modest． 别谦虚了。  
Don't count on me．别指望我。  
Don't fall for it! 别上当!  
Don't flatter me. 过奖了。  
Don't get high hat. 别摆架子。 
Don't get loaded. 别喝醉了。 
Don't get me wrong. 别误会我。 
Don't give me that! 少来这套!  
Don't let me down． 别让我失望。  
Don't let me down. 别让我失望。  
Don't lose your head。 不要惊慌失措。  
Don't make up a story. 不要捏造事实。 
Don't mention it. 没关系，别客气。  
Don't move! 不许动!  
Don't over do it. 别太过分了。 
Don't play possum! 別裝蒜！ 
Don't push me. 别逼我。  
Don't take ill of me. 别生我气。  
Don't trust to chance! 不要碰运气。  
Don't worry． 别担心。  
Drop it! 停止！ 
Easy come easy go． 来得容易，去得快。  
Easy does it. 慢慢来。  
Enjoy yourself! 祝你玩得开心!  
Excuse me，Sir． 先生，对不起。  
Fasten your seat belt． 系好你的安全带。 
Feel better? 好点了吗?  
Follow me． 跟我来。  
Follow my nose. 凭直觉做某事。 
Forget it! 休想! (算了!)  
Fresh paint! 油漆未干！ 
Get an eyeful. 看个够。 
Get cold feet. 害怕做某事。 
Get out of here! 滚出去！ 
Gild the lily. 画蛇添足。 
Give me a hand! 帮帮我!  
Go ahead. 继续。 
Go down to business. 言归正传。  
Go to hell！ **吧！ 
God works. 上帝的安排。  
Good for you! 好得很！ 
Good job! 做得好!  
Good luck! 祝好运!  
Good luck! 祝你好运！ 
Guess what? 猜猜看?  
Hang on! 抓紧（别挂电话）！ 
Have a good of it.玩的很高兴。  
Have fun! 玩得开心!  
He always talks big． 他总是吹牛。  
He came by train． 他乘火车来。  
He can hardly speak． 他几乎说不出话来。  
He can't take a joke． 他开不得玩笑。  
He has a quick eye. 他的眼睛很锐利。 
He has an ax to grind. 他另有企图。 
He is a fast talker. 他是个吹牛大王。 
He is a smart boy． 他是个小机灵鬼。  
He is ill in bed． 他卧病在床。  
He is just a child． 他只是个孩子。  
He is my age． 他和我同岁。  
He is the pain on neck. 他真让人讨厌。 
He lacks courage． 他缺乏勇气。  
He neither drinks nor smokes. 他既不喝酒也不抽烟。 
He neither drinks nor smokes. 他既不喝酒也不抽煙。 
He owes my uncle $．他欠我叔叔美元。  
He pushes his luck. 他太贪心了。 
He won an election． 他在选举中获胜。  
Help me out. 帮帮我。 
Help yourself． 别客气。  
Here we are! 我们到了！ 
Here ye! 说得对！ 
Here you are． 给你。  
High jack! 举起手来（抢劫）！ 
Hit the ceiling. 大发雷霆。 
Hold on． 等一等。  
Hope so. 希望如此。  
How about eating out？ 外面吃饭怎样？ 
How are things going? 事情进展得怎样?  
How are you recently? 最近怎么样?  
How big of you! 你真棒！ 
How come… 怎么回事，怎么搞的。  
How much? 多少钱?  
How's everything? 一切还好吧?  
How's it going? 怎么样?  
I agree。 我同意。  
I am a football fan． 我是个足球迷。  
I am all ears. 我洗耳恭听。 
I am the one wearing pants in the house. 我当家。  
I beg your pardon． 请你原谅。  
I beg your pardon? 请您再说一遍(我没有听清)。  
I can't follow you． 我不懂你说的。  
I can't make both ends meet. 我上个月接不到下个月，缺钱。 
I decline! 我拒绝!  
I don't care. 我不在乎。  
I don't have anywhere to be. 没地方可去。 
I don't mean it. 我不是故意的。  
I doubt it 我怀疑。  
I felt sort of ill. 我感觉有点不适。  
I have a good idea! 我有一个好主意。  
I have no choice． 我别无选择。  
I have no idea． 我没有头绪。  
I have to be late and keep my date waiting. 我不喜欢迟到而让别人久等。 
I just made it! 我做到了!  
I know all about it． 我知道有关它的一切。  
I like ice-cream． 我喜欢吃冰淇淋。  
I lost my way. 我迷路了。 
I might hear a pin drop. 非常寂静。 
I promise． 我保证。  
I quit! 我不干了!  
I see． 我明白了。  
I stay at home a lot. 我多半在家里。 
I swear by the god. 我对天发誓。 
I think so． 我也这么想。  
I wonder if you can give me a lift？ 能让我搭一程吗？ 
If only I could fly． 要是我能飞就好了。  
I'll be back soon． 我马上回来。  
I'll be right there． 我马上就到。  
I'll be seeing you. 再见。 
I'll check it out． 我去查查看。  
I'll fix you Up． 我会帮你打点的。 
I'll get even with him one day. 我总有一天跟他扯平 
I'll kick you ***. 我将炒你鱿鱼。 
I'll see to it 我会留意的。  
I'll see you at six． 我六点钟见你。  
I'll try my best． 我尽力而为。  
I'm afraid I can't. 我恐怕不能。 
I'm bored to death. 我无聊死了。 
I'm dying to see you. 我很想见你。 
I'm full． 我饱了。  
I'm going to go. 我這就去。  
I'm his fan。 我是他的影迷。  
I'm home． 我回来了。  
I'm in a hurry! 我在赶时间!  
I'm lost． 我迷路了。  
I'm not going. 我不去了。  
I'm not it a good mood. 没有心情（做某事）。 
I'm on a diet． 我在节食。  
I'm On your side． 我全力支持你。  
I'm single． 我是单身贵族。  
IS it true or false? 这是对的还是错的?  
Is it yours? 这是你的吗?  
Is that so？ 是这样吗？ 
It can be a killer. 这是个伤脑筋的问题。 
It doesn't make any differences. 没关系。  
It doesn't take much of you time. 这不花你好多时间。 
It doesn't work. 不管用。  
It is a deal！ 一言为定！ 
It is a long story. 一言难尽。  
It is a small world! 世界真是小！ 
It is growing cool． 天气渐渐凉爽起来。  
It is not a big deal! 没什么了不起！  
It is of high quality. 它质量上乘。 
It is raining. 要下雨了。 
It is urgent. 有急事。  
It really takes time． 这样太耽误时间了。  
It seems all right． 看来这没问题。  
It sounds great!． 听起来很不错。  
It was something that happens once in the blue moon. 这是千载难逢的事。 
It’s a long story． 说来话长。  
It’s Sunday today． 今天是星期天。  
It's a fine day。 今天是个好天。  
It's against the law． 这是违法的。  
It's going too far． 太离谱了。  
It's her field． 这是她的本行。  
It's up in the air. 尚未确定。 
It's up to you. 由你决定。 
It's up to you． 由你决定。  
Just read it for me． 就读给我听好了。  
Just wait and see! 等着瞧!  
Just wonderful! 简直太棒了!  
Keep in Touch． 保持联络。  
Keep it up! 坚持下去!  
Knowledge is power． 知识就是力量。  
Leave me alone. 别理我。 
Let go! 放手!  
Let me see．让我想想。  
Let's bag it. 先把它搁一边。 
Let's play it by ear. 让我们随兴所至。 
Long time no see! 好久不见!  
Lose head. 丧失理智。 
Love me，love my dog． (谚语)爱屋及乌。  
Make it up! 不记前嫌！ 
Make it. 达到目的，获得成功。 
Make up your mind． 做个决定吧。  
May I use your pen? 我可以用你的笔吗?  
Me too． 我也是。  
Move out of my way! 让开!  
My girlfriend and I broke up. 我和我的女朋友吹了。 
My god! 天哪!  
My hands are full right now. 我现在很忙。 
My mouth is watering． 我要流口水了。  
My treat． 我请客。  
Never mind. 不要緊。  
Never mind．不要紧。  
No one knows . 没有人知道。  
No pain，no gain． 不劳无获。  
No problem! 没问题!  
No way! 不可能！  
No way! 不行!  
None of my business. 不关我事。  
None of you keyhole. 不准偷看。 
Not at all. 根本就不（用）。 
Not bad． 还不错。  
Not in the long run. 从长远来说不是这样的。 
Not precisely! 不见得，不一定！ 
Not so bad. 不错。  
Not yet． 还没。  
Nothing tricky. 别耍花招。 
Nuts! 呸；胡说；混蛋！ 
Nuts! 呸；胡說；混蛋 
Of course! 当然了!  
Play hooky. 旷工、旷课。 
Poor thing! 真可怜！ 
Poor thing! 真可憐！ 
Price is soaring, if it goes on like this, we shall not be able to keep the pot boiling. 物价直线上升，这样子下去，我们锅里可没什么东西煮饭。 
Right over there. 就在那里。 
Say hello to everybody for me. 替我向大家问好。 
See you． 再见。  
She had a bad cold． 她患了重感冒。  
She is still mad at me. 她还在生我的气。 
She make a mess of things. 她把事情搞得一塌糊涂。  
She'll be along in a few minutes. 他马上会过来。 
She's got quite a wad. 她身怀巨款。 
Shoot the breeze. 闲谈。 
Shut up! 闭嘴!  
Side dish. 配菜。 
Sleeping on both ears. 睡的香。 
Slow down! 慢点!  
So do I． 我也一样。  
So far，So good． 目前还不错。  
So long． 再见。  
Speak louder，please． 说话请大声点儿。  
Stay away from him. 别*近他。 
Still up？ 还没睡呀？  
Sure thin! 當然！  
T can't help it. 我情不自禁。  
Take a seat! 请坐！ 
Take care! 保重!  
Take it easy． 别紧张。  
Talk truly. 有话直说。 
Tell me when! 随时奉陪！ 
That is a boy! 太好了，好极了！ 
That is great! 太棒了！ 
That is unfair. 这不公平！ 
That rings a bell. 听起来耳熟。 
That's a good idea． 这个主意真不错。  
That's all I need． 我就要这些。  
That's all! 就这样!  
That's neat． 这很好。  
The answer is zero． 白忙了。  
The line is engaged. 占线。 
The view is great． 景色多么漂亮!  
The wall has ears． 隔墙有耳。  
There comes a bus． 汽车来了。  
There is nobody by that name working here. 这里没有这个人。 
There is nobody by that name working here.這裡沒有這個人。  
They hurt． (伤口)疼。  
This boy has no job． 这个男孩没有工作。  
This house is my own． 这所房子是我自己的。  
This way。 这边请。  
Thousand times no! 绝对办不到！  
Time is money． 时间就是金钱。  
Time is running out． 没时间了。  
Time is up． 时间快到了。  
To be careful! 一定要小心!  
Try again． 再试试。  
Wait and see. 等着瞧。 
Watch out! 当心。  
Watch you mouth. 注意言辞。 
We are good friends． 我们是好朋友。  
We have no way out. 我们没办法。 
Well，it depends 噢，这得看情况。  
We're all for it． 我们全都同意。  
What a good deal! 真便宜!  
What a pity! 太遗憾了!  
What about you? 你呢?  
What brought you here？ 什么风把你吹来了？ 
What day is today? 今天星期几?  
What do you think? 你怎么认为？  
What does she like? 她喜欢什么?  
What happened to you? 你怎么了?  
What if I go for you？ 我替你去怎么样？ 
What is the fuss？ 吵什么？  
What is you major？ 你学什么专业？ 
What should I do? 我该怎么办？  
What time is it? 几点了?  
What's new? 有什么新鲜事吗?  
What's up? 有什么事吗?  
What's your trouble? 你哪儿不舒服?  
When are you leaving？ 你什么时候走？ 
Who knows! 天晓得！  
Who told you that? 谁告诉你的?  
Who wants？ 谁稀罕？ 
Who's calling? 是哪一位?  
Who's kicking off? 现在是谁在开球?  
Why are you so sure？ 怎么这样肯定？ 
Why die she marry a man old enough to be her father？ 她为什么要嫁给一个年龄与她父亲相当的男人？ 
Why not? 好呀! (为什么不呢?)  
Why so blue？ 怎么垂头丧气？ 
Would you mind making less noise? 能不能小声点。 
Yes，I suppose So． 是的，我也这么认为。  
You are just in time. 你来得正是时候。  
You are welcome! 别客气！ 
You ask for it! 活该！ 
You asked for it! 你自讨苦吃!  
You bet! 一定，当然！ 
You can make it! 你能做到!  
You can't miss it 你一定能找到的。  
You did fairly well! 你干得相当不错  
You did right． 你做得对。  
You don't say so. 未必吧，不至于这样吧。 
You don't say! 真想不到！ 
You don't seem to be quite yourself today. 你今天看起来不大对劲。  
You have my word． 我保证。  
You might at least apologize. 你顶多道个歉就得了。 
You need to workout． 你需要去运动锻炼一下。  
You never know. 世事难料。 
You owe me one．你欠我一个人情。  
You set me up! 你出卖我!  
You want a bet？ 你想打赌吗？ 
Your are welcome. 你太客气了。  
Your hand feels cold． 你的手摸起来很冷。。  
You're welcome． 不客气。
久仰！I've heard so much about you. 
好久不见了！Long time no see. 
辛苦了！You've had a long day. You've had a long flight. 
尊敬的朋友们！Distinguished/Honorable/Respected friends 
阁下(多用于称呼大使) Your Excellency 
为…举行宴会/宴请Host a dinner/banquet/luncheon in honor of … 
 欢迎宴会Welcome dinner 
 便宴Informal dinner 
 午宴(附有情况介绍或专题演讲等内容)Luncheon 
 便餐Light meal 
 工作午餐Working luncheon 
 自助餐 Buffet dinner/luncheon 
答谢宴会Return dinner 
告别宴会Farewell dinner 
庆功宴Glee feast 
招待会Reception 
庆祝中华人民共和国成立四十五周年招待会Reception Celebrating the 45th Anniversary of the Founding of the People's Republic of China 
鸡尾酒会Cocktail party 
茶话会Tea party 
包餐/点餐Table d'hote/a la carte 
上菜Serve a courst 
您的位置在这里。Here is your seat. 
请入席！Please have a seat. 
欢聚一堂Enjoy this happy get-together 
请随便！Please yourself at home./Please enjoy yourself. 
请各位随意用餐。Help yourself please. 
您喝点么？What would you like to drink? 
 
请各位举杯并同我一起为所有在座的朋友们的健康干杯！I'd ask you to raise your glass and join me in a toast ot the health of all our friends present here. 
敬您一杯！Here's to you!  
祝你健康！To your health!   
我要为此干杯！I'll drink to that! 
随量！Whatever you like! 
我失陪一会儿！Excuse me for a minute. 
菜不好，请多多包涵！Hope you enjoy yourself. 
女士们先生们，欢迎各位光临，演出很快就要开始了，请尽快就坐。Ladies and gentlemen, good evening. The concert/show would start soon. Please get yourself seated. Thank you.   
出席今天招待会的贵宾有…The distinguished guests paarticipating the reception are … 
现在请…讲话I have the honour to call upon … 
隆重庆祝Grand celebration 
 值此节日之际致以节日的祝贺！On the occasion of the season, I would like to extend season's greetings. 
祝您工作顺利、事业成功、身体健康、家庭幸福！Wish you the very best of luck in your job, every success in your future endeavours, good health and a happy family! 
衷心祝贺您当选…Hearty congratulations on your recent election as … 
 举行会议/研讨会/大会/座谈会/学术报告会Hold a meeting/seminar/conference/forum/symposium 
  
赞助人/主办人/承办人/协办人Patron/sponsor/organizer/co-organizer 
举行谈判Enter into negotiation 
交涉Make representations with sb. On sth./deal with sb. 
事物性会谈Talks at working level 
对口会谈Counterpart talks 
议程项目Items on the agenda 
主题Theme 
议题Topic for discussion 
双方商定的议程Schedule mutually agreed upon 
开幕会议 Opening session 
全体会议Plenary session 
开场白Introduction 
情况介绍Presentation 
小组讨论Panel discussion 
同有关单位磋商Hold consultations with the organizations concerned 
一轮会谈One round of talks 
决议Resolution 
谅解备忘录Memorandum of understanding 
现在开会。I declare the meeting open. 
请…发言。I invite the representative of …To take the floor下面我给各位简要介绍一下北京的经济情况Now I would like to give you a brief overview of Beijing's economy. 
 我的介绍完了，谢谢！That's all for my presentation. thank you 
我先说这么多。So much for my remarks for now. 
 我要说的就是这些。That's all for what I want to say. 
 您看是先谈原则问题呢，还是先谈具体问题？I wonder if you would like to start with matters of principle or specific issues? 
让我先谈一个问题。If you agree(With your permission), let me start with one issue 
在谈那个问题之前我想对您刚才讲的话谈点看法。Before we turn to that issue, I wish to make a few comments/remarks on your presentation. 
 您对此事怎么看呢？I wish to benefit from your views on this matter./ What is your view on this matter?/ How do you see this matter? 
我提议休会十分钟。I propose a ten-minute break. 
 我想接着刚才的问题讲下去。I will pick up where we left off just now. 
对不起，我插一句。Sorry for the interruption but 
  
当然可以！By all means. 
 怎么都行！Whatever you say.  
我没有异议。I have no objection. 
我方对这个问题有异议。We take exception to this question.我们高兴地看到…We note with pleasure that … 
 这个日期贵方觉得合适吗？I wonder if this date would be suitable for you? 
 不知你们上午谈的怎样？I wonder how the meeting went this morning? 
我方很希望 贵方能尽早给予肯定的答复。We would greatly appreciate it if you could give us your favourable and prompt commitment as soon as possible. 
 请你们务必在8月1日前提出意向书。You are kindly requested to submit the letter of intent on the date no later than 1st August. 
 纠缠这个问题。Entangle this issue. 
密切注视Keep close watch on 
促进密切合作Spur/promote intensive cooperation 

#T=背景调查
Applicant's Verified Dates of Employment:
It might be from end of 2006 to beginning of 2010.	

Applicant's Verified Title / Position:
Consultant.	

What Was Your Business Relationship with the Applicant?
Supervisor and colleague.	

What Was the Nature of the Position the Applicant Held? What Were the Key Components the Applicant's Position?
This position is supposed to be involved in software development, customer maintenance and team management as well.	

How Many Days Was He / She Absent? (Number of Days Absent in an Average Year Which Was Not Related to a Disability)
Not much, takes a day off occasionally.	

What Were the Reasons for the Absenteeism?
No absenteeism on purpose.	

Was This Applicant Punctual for Work? If No, Why?
Yes.	

How Would You Rate/Comment The Applicant's Work Performance?
Excellent.	

How Would You Rate/Comment The Applicant's Work Ethic?
Very well.	

How Would You Rate/Comment The Applicant's Product Knowledge?
Pretty good.	

How Would You Rate/Comment The Applicant's Interpersonal Skills?
Very impressive.	

How Would You Rate/Comment The Applicant's Communication Skills?
Very good.	

How Would You Rate/Comment The Applicant's Speed and Accuracy?
Very well.	

How Would You Rate/Comment The Applicant's Attitude?
Very positive attitude.	

How Would You Rate/Comment The Applicant's Level of Cooperation?
Very easy and comfortable to cooperate.	

How Would You Rate/Comment The Applicant's Customer Service Skills?
Very patient and professional. Strong skills.	

How Would You Rate/Comment The Applicant's Reliability?
Very reliable.	

How Would You Rate/Comment The Applicant's Assertiveness?
Even influenced people around him.	

How Would You Rate/Comment The Applicant's Objectivity?
Very objective.	

How Would You Rate/Comment The Applicant's Ability to Supervise / Manage?
Strong ability.	

How Would You Rate/Comment The Applicant's Multitasking Ability?
Strong ability to handle multitasking situation.	

How Would You Rate/Comment The Applicant's Interaction With Others (Team Player)?
Absolutely a Team Player.	

How Would You Rate/Comment The Applicant's Ability to Adapt to the Environment?
Very impressive.	

What Were This Applicant's Strengths?
Strong technique and communication skills. Very enthusiastic and positive. Good leader and partner of the team.	

In What Areas Did This Applicant Require Improvement?
I have to say not much.	

Did This Applicant Meet Performance Target Expectations Set Out for Them? (Yes, No, N/A)
Yes.	

What Was The Applicant's Reason for Leaving Your Company? (LaidOff, Resigned, Terminated, Other, N/A)
Resigned.	

Was Any Disciplinary Action or Cautionary Words Ever Taken or Spoken Against Him / Her? If Yes, What?
No.	

Would You Rehire This Person? If No, Why?
Yes.	

Do You Have Any Additional Comments?
Hope everything is okay for him in Canada ?	

Source Information (Name, Title, Company)
Xiyue Yu

Microsoft (China)	



#T=出国实用英语(2)
4.家居日用品
refrigerator 冰箱  
automatic rice cooker 电饭锅  
steamer 蒸锅  
oven 烤箱  
grill 烧烤架  
toaster 烤面包机  
egg beater 打蛋器  
ice crusher 刨冰机  
food processor 食品加工机  
paper towel 纸巾  
apron 围裙  
tableware 餐具  
plate 盘子  
dish 碟子  
bowl 碗  
cupboard 碗橱  
dining table 餐桌  
larder 食品柜  
drop-leaf table 可以折叠边缘的桌子  
chopping board 案板  
cutlery tray 装餐具的容器  
dish drainer 晾干餐具的容器（类似铁丝筐）  
table cloth 桌布
laundry bag 洗衣袋  
pail 洗衣桶  
ironing board 烫衣板  
steam and dry iron 蒸汽电熨斗  
electric iron 电熨斗  
laundry drier 烘干机  
spin-drier 旋转式脱水机  
washing machine 洗衣机  
radiator 暖气片  
electric fan 电扇  
stand fan 落地电扇  
oscillating fan 摇头电扇  
bed light/bed lamp 床头灯  
fluorescent lamp 日光灯  
ceiling lamp/pendant lamp 吊灯  
desk/table lamp 台灯  
wall light 壁灯  
floor lamp 落地灯  
chandelier 枝状吊灯
water gauge 水表  
plug 插头  
outlet/receptacle 插座 
paste 浆糊  
glue 胶水  
adhesive tape 胶条  
packing paper 包装纸  
string 绳子  
carpenter 木工  
electrician 电工  
utility man 杂务工  
plumber 管道工  
painter 油漆工  
vacuum hose holder 吸尘器管子的托架  
watering can 浇水壶
blanket 毛毯  
cushion 垫子  
quilt 被子  
cotton terry blanket 毛巾被  
feather quilt 羽绒被  
cotton quilt 棉被  
bedding 床上用品  
mosquito net 蚊帐  
pillow 枕头  
bolster 长枕  
pillow case 枕套  
tick 褥子 
carpet 地毯 （一般指大的整块的，铺房间的那种） 
rug 地毯（一般指小块的，放在沙发等边上的那种）
bathtub 浴缸  
hand shower 手握式淋浴器  
shower nozzle 喷头  
tap faucet 水龙头  
plastic curtain 防水浴帘  
shower cap 浴帽  
bath slipper 洗澡用拖鞋  
bath mat 防滑垫  
towel hanger/holder 毛巾架  
towel ring 毛巾环  
bath towel 浴巾  
soap stand 肥皂盒  
comb 梳子  
soap 肥皂  
shampoo 洗发露  
conditioner 护发素  
dryer 吹风机 
razor 刮胡刀
toothbrush 牙刷                             toothpaste 牙膏 
bed frame/bed base 床架 
bed frame/bed base 床架                    headboard 床头板 
sofa bed 沙发床  
folding guest bed 折叠床 
loftbed frame架在空中的床（下面可放沙发、桌子等）  
bunkbed frame 上下铺的床  
slatted bed base 板条床  
sprung base 弹簧床  
bedspread 床罩  
sheet 床单  
mat 席子  
mattress 床垫 （厚的那种）  
mattress pad 床垫 (薄的那种)  
bed canopy 支在床上的篷子 （一般用于儿童床上的装饰）  
bedside table 床头柜
Banqueting chair 宴会椅 
Barstool 吧椅 
Bathroom accessories 浴室配套装置 
Bathroom combination 浴室组合柜 
Bathroom consoles 浴室多用架 
Bathroom furniture 浴室家具 
Bathroom vanity 浴室盥洗台 
Birch door 桦木门 
Board-room and conference table 会议桌 
Bookcase 书柜 
Bookshelf 书架 
Built-in kitchen 配套厨房家具 
Bunk 双层床 
Bunk bed 双层床 
Children’s chair 儿童椅 
CKD(complete knock down) 整体拆装式家具 
Clothes rail 挂衣杆 
Cocktail cabinet 吧柜，酒柜 
Cocktail table 鸡尾酒桌 
Coffee table 茶几，咖啡桌 
Combine-unit 组合柜 
Composite furniture 复合家具 
Console 小桌                                       Contract programmes 订做家具 
Cot 童床（婴儿床） 
Couch 长沙发椅 
Cupboard 橱柜 
Cupboard wall unit for flat 套房衣柜 
Curtain 窗帘，挂帘 
Customized furniture 订做家具
Double-bed 双人床 
Double function sofa-bed 双人沙发床 
Double sided  mirror 双面镜 
Draughtsman chair 吧椅 
Drawer 抽屉 
Dressing table 梳妆台
Easy chair 轻便椅 
End table 茶几 
Entrance hall furniture 门厅家具 
Exterior door户外门
Filing cabinet 文件柜 
Fireplace壁炉 
Fitment 固定家具 
Fitting 家居用品 
Flower stand 花架 
Folding chair 折叠椅 
Folding furniture 折叠家具 
Folk furniture 民间家具
Junior desk chair 学生书桌椅
Kitchen block /kitchen rock 厨房地砖 
Kitchen cabinet 餐具柜 
Kitchen chair, stool and bench 厨房椅、圆凳及条椅 
Kitchen fitment 厨房固定家具 
Kitchen table 厨房餐桌 
Kitchen unit 厨房成套家具
Mirror for chest of drawers 多屉柜梳妆镜 
Multi-purpose sofa 多用沙发 
Multi-purpose table 多用桌
Nest 茶几
Occasional furniture 配套家具，休闲家具 
Occasional table 休闲桌 
Office furniture 办公家具 
Office seating 办公座椅 
Office table 办公桌 
Partition wall 隔断
School table 课桌 
screen 屏风 
Seat 座椅 
secretaire 写字桌(尤指有抽屉及分类格者) 
Secretarial chair 秘书椅 
sectional sofa 拼合沙发 
semi-CKD 半拆装家具 
separate wine cabinet 独立厨柜 
serving table 送餐桌 
settee; chaise longue 长靠椅 
shelving combination 组合架 
shoe rack 鞋架 
side table 小桌 
sideboard 餐具柜 
simmous bed 席梦思床 
single bed 单人床 
slat stool 板条凳 
sleeper sofa 可睡沙发 
sofa 沙发 
sofa bed 沙发床 
sofa table 沙发桌 
soft chair 软椅 
spring bed; steel cot 钢丝床；弹簧床 
spring-seat chair 弹簧座椅 
square stool 方凳 
square table 方桌 
steel chair 扶手椅 
steel desk 钢制写字台 
steel safe 保险柜 
step stool 梯凳 
stool 凳子；搁脚凳 
storage for umbrellas 伞架 
straight back chair 直背椅 
strong box; safe 保险箱 
studio couch 单人沙发床 
suitcase; trunk 衣箱；小型旅行箱 
swivel armchair 帆布折叠躺椅 
swivel-top stool 转动凳
5.食品
水果类（fruits）：  

西红柿 tomato 菠萝 pineapple 西瓜watermelon 香蕉banana 柚子 shaddock （pomelo） 橙子orange 苹果apple 柠檬lemon 樱桃 cherry 桃子peach 梨 pear 枣Chinese date （去核枣 pitted date ） 椰子coconut 草莓 strawberry 树莓 raspberry 蓝莓 blueberry 黑莓 blackberry 葡萄 grape 甘蔗 sugar cane 芒果 mango 木瓜 pawpaw或者papaya 杏子 apricot 　油桃 nectarine 柿子persimmon 石榴pomegranate 榴莲 jackfruit 槟榔果 areca nut （西班牙产苦橙）bitter orange 猕猴桃 kiwi fruit or Chinese gooseberry 金橘cumquat 蟠桃 flat peach 荔枝 litchi 青梅greengage 山楂果 haw 水蜜桃honey peach 香瓜，甜瓜 musk melon 李子plum 杨梅 waxberry red bayberry 桂圆 longan 沙果 crab apple 杨桃starfruit 枇杷 loquat 柑橘 tangerine 莲雾wax-apple 番石榴 guava  

肉、蔬菜类（livestock家畜）：  

南瓜（倭瓜） pumpkin cushaw 甜玉米 Sweet corn 牛肉beef 猪肉pork 羊肉 mutton 羔羊肉lamb 鸡肉chicken 生菜 莴苣lettuce 白菜 Chinese cabbage （celery cabbage）（甘蓝）卷心菜 cabbage 萝卜 radish 胡萝卜 carrot 韭菜leek 木耳 agarics 豌豆 pea 马铃薯（土豆） potato 黄瓜 cucumber 苦瓜 balsam pear 秋葵 okra 洋葱 onion 芹菜 celery 芹菜杆 celery sticks 地瓜 sweet potato 蘑菇 mushroom 橄榄 olive 菠菜spinach 冬瓜 （Chinese）wax gourd 莲藕 lotus root 紫菜 laver 油菜 cole rape 茄子 eggplant 香菜 caraway 枇杷loquat 青椒 green pepper 四季豆 青刀豆 garden bean 银耳 silvery fungi 腱子肉tendon 肘子 pork joint 茴香fennel（茴香油fennel oil 药用） 鲤鱼carp 咸猪肉bacon 金针蘑 needle mushroom 扁豆 lentil 槟榔 areca 牛蒡great burdock 水萝卜 summer radish 竹笋 bamboo shoot 艾蒿Chinese mugwort 绿豆mung bean 毛豆green soy bean 瘦肉 lean meat 肥肉speck 黄花菜 day lily （day lily bud） 豆芽菜 bean sprout 丝瓜 towel gourd (注：在美国丝瓜或用来做丝瓜茎loofah洗澡的，不是食用的)  

海鲜类（sea food）：  

虾仁 Peeled Prawns 龙虾 lobster 小龙虾 crayfish（退缩者） 蟹 crab 蟹足crab claws 小虾（虾米） shrimp 对虾、大虾 prawn （烤）鱿鱼（toast）squid 海参 sea cucumber 扇贝 scallop 鲍鱼 sea-ear abalone 小贝肉cockles 牡蛎oyster 鱼鳞scale 海蜇jellyfish鳖 海龟turtle 蚬 蛤 clam 鲅鱼 culter 鲳鱼 butterfish 虾籽 shrimp egg 鲢鱼 银鲤鱼chub silver carp 黄花鱼 yellow croaker  

调料类（seasonings）：  

醋 vinegar 酱油 soy 盐 salt 加碘盐 iodized salt 糖 sugar 白糖 refined sugar 酱 soy sauce 沙拉 salad 辣椒 hot（red）pepper 胡椒 （black）pepper 花椒wild pepper Chinese prickly ash powder 色拉油salad oil 调料 fixing sauce seasoning 砂糖 granulated sugar 红糖 brown sugar 冰糖 Rock Sugar 芝麻 Sesame 芝麻酱 Sesame paste 芝麻油 Sesame oil 咖喱粉curry 番茄酱（汁） ketchup redeye 辣根horseradish 葱 shallot （Spring onions） 姜 ginger 蒜 garlic 料酒 cooking wine 蚝油oyster sauce 枸杞（枇杷,欧查果 ） medlar 八角aniseed 酵母粉yeast barm 　　Yellow pepper 黄椒 肉桂 cinnamon (在美国十分受欢迎，很多事物都有肉桂料) 黄油 butter 香草精 vanilla extract(甜点必备) 面粉 flour 洋葱 onion  

主食类（staple food）：  

三文治 sandwich 米饭rice 粥 congee （rice soup） 汤 soup 饺子dumpling 面条 noodle 比萨饼 pizza 方便面 instant noodle 香肠 sausage 面包 bread 黄油 （白塔油）butter 茶叶蛋 Tea eggs 油菜 rape 饼干 cookies 咸菜（泡菜）pickle 馒头 steamed bread 饼（蛋糕）cake 汉堡 hamburger 火腿ham 奶酪 cheese 馄饨皮 wonton skin 高筋面粉 Strong flour 小麦wheat 大麦barley 青稞highland barley 高粱broomcorn （kaoliang ）春卷Spring rolls 　芋头 Taro 山药yam 鱼翅 shark fin 黄花 daylily 松花蛋 皮蛋preserved eggs 春卷 spring roll 肉馅饼minced pie 糙米 Brown rice 玉米 corn 馅儿 stuffing 开胃菜 appetizer 面粉 flour 燕麦 oat 白薯 甘薯 sweet potato牛排 steak 里脊肉 fillet 凉粉 bean jelly 糯米 江米 sticky rice 燕窝 bird's nest 粟 Chinese corn 肉丸子 meat balls 枳橙citrange 点心（中式）dim sum 淀粉starch 蛋挞 egg tart  

（dry fruits）干果类 ：  

腰果 Cashew nuts 花生 peanut 无花果fig 榛子filbert hazel 栗子chestnut 核桃 walnut 杏仁almond 果脯 preserved fruit 芋头taro 葡萄干raisin cordial 开心果 pistachion 巴西果 brazil nut 菱角,荸荠 water chestnut (和国内食用法不同，做坚果食用)  

酒水类（beverage）：  

红酒 red wine 白酒 white wine 白兰地 brandy 葡萄酒 sherry 汽水(软饮料) soda （盐）汽水sparkling water 果汁juice 冰棒 Ice-lolly 啤酒beer 酸奶 yoghurt 伏特加酒vodka 鸡尾酒cocktail 豆奶 soy milk 豆浆soybean milk 七喜 7 UP 麒麟（日本啤酒kirin） 凉开水 cold boiled water 汉斯啤酒 Hans beer 浓缩果汁 concentrated juice 冰镇啤酒 iced(chilled ) beer 札幌（日本啤酒）Sapporo 爱尔啤酒（美国）ale A级牛奶 grand A milk 班图酒bantu beer 半干雪利 dry sark 参水牛奶 blue milk 日本粗茶 bancha 生啤酒 draft beer 白啤酒 white beer <苏格兰>大麦酒barley-bree 咖啡伴侣coffee mate  

零食类（snack）:  

mint 薄荷糖 cracker饼干, biscuit饼干, 棒棒糖bonbon 茶tea （沏茶 make the tea） 话梅prune candied plum 锅巴 rice crust 瓜子 melon seed 冰棒（冰果） ice（frozen） sucker 冰淇凌ice cream 防腐剂preservative 圣代冰淇淋 sundae 巧克力豆 marble chocolate barley 布丁pudding  

与食品有关的词语（some words about food）:  

炸 fired 炝 quick boiled 烩 braise （烩牛舌 braised ox tongue） 烤 roast 饱嗝 burp 饱了 饱的 full stuffed 解渴quench thirst （形容食物变坏spoil spoilage） preservative 防腐剂 expiration date 产品有效期 （形容酒品好： a good strong brew 绝味酿 ）  

应各位要求补充的中式西式食物  



中式早點：  

烧饼　Clay oven rolls 油条　Fried bread stick 韭菜盒　Fried leek dumplings 水饺Boiled dumplings 蒸饺　Steamed dumplings 馒头　Steamed buns 割包Steamed sandwich 饭团　Rice and vegetable roll 蛋饼　Egg cakes 皮蛋　100-year egg 咸鸭蛋　Salted duck egg 豆浆　Soybean milk  

饭 类：  

稀饭　　Rice porridge 白饭　Plain white rice 油饭 Glutinous oil rice  
糯米饭　Glutinous rice 卤肉饭　Braised pork rice 蛋炒饭　Fried rice with egg  
地瓜粥　Sweet potato congee  

面 类：  

馄饨面 Wonton & noodles 刀削面 Sliced noodles 麻辣面Spicy hot noodles 麻酱面　Sesame paste noodles 鴨肉面 Duck with noodles 鱔魚面 Eel noodles 乌龙面　Seafood noodles 榨菜肉丝面　Pork , pickled mustard green noodles 牡蛎细面　Oyster thin noodles 板条　Flat noodles 米粉 Rice noodles 炒米粉　Fried rice noodles 冬粉Green bean noodle　  

汤 类：  

鱼丸汤　Fish ball soup 貢丸汤　Meat ball soup 蛋花汤　Egg & vegetable soup 蛤蜊汤　Clams soup 牡蛎汤　Oyster soup 紫菜汤　Seaweed soup 酸辣汤　Sweet & sour soup 馄饨汤　Wonton soup 猪肠汤　Pork intestine soup 肉羹汤　Pork thick soup 鱿鱼汤 Squid soup 花枝羹　Squid thick soup  

中餐：  

bear's paw 熊掌 * of deer 鹿脯 beche-de-mer; sea cucumber 海参  
sea sturgeon 海鳝 salted jelly fish 海蜇皮kelp,seaweed 海带 abalone鲍鱼shark fin鱼翅scallops干贝lobster龙虾 bird's nest 燕窝 roast suckling pig 考乳猪  

pig's knuckle 猪脚 boiled salted duck 盐水鸭 preserved meat 腊肉 barbecued pork 叉烧 sausage 香肠 fried pork flakes 肉松 BAR-B-Q 烤肉 meat diet 荤菜 vegetables 素菜 meat broth 肉羹 local dish 地方菜 Cantonese cuisine 广东菜 set meal 客饭 curry rice 咖喱饭  
fried rice 炒饭 plain rice 白饭 crispy rice 锅巴  
gruel, soft rice , porridge 粥 —noodles with gravy 打卤面 plain noodle 阳春面 casserole 砂锅 chafing dish,fire pot火锅 meat bun肉包子  
shao-mai烧麦preserved bean curd 腐乳bean curd豆腐 fermented blank bean 豆豉 pickled cucumbers 酱瓜 preserved egg 皮蛋 salted duck egg 咸鸭蛋 dried turnip 萝卜干  

西餐与日本料理：  

menu 菜单French cuisine法国菜 today's special 今日特餐 chef's special 主厨特餐 buffet 自助餐 fast food 快餐 specialty 招牌菜 continental cuisine 欧式西餐 aperitif 饭前酒 dim sum 点心 French fires炸薯条baked potato烘马铃薯 mashed potatoes马铃薯泥omelette 简蛋卷 pudding 布丁 pastries 甜点 pickled vegetables 泡菜 kimchi 韩国泡菜 crab meat 蟹肉 prawn 明虾 conch 海螺 escargots 田螺braised beef 炖牛肉 bacon 熏肉 poached egg 荷包蛋 sunny side up 煎一面荷包蛋 over 煎两面荷包蛋 fried egg 煎蛋 over easy 煎半熟蛋 over hard 煎全熟蛋 scramble eggs 炒蛋 boiled egg 煮蛋 stone fire pot 石头火锅 sashi 日本竹筷 sake 日本米酒  
miso shiru 味噌汤 roast meat 铁板烤肉 sashimi 生鱼片 butter 奶油
6.中国特色
1.      元宵节： Lantern Festival 
2.      刺绣：embroidery 
3.      重阳节：Double-Ninth Festival 
4.      清明节：Tomb sweeping day 
5.      剪纸：Paper Cutting 
6.      书法：Calligraphy 
7.      对联：(Spring Festival) Couplets 
8.      象形文字：Pictograms/Pictographic Characters 
9.      人才流动：Brain Drain/Brain Flow 
10.  四合院：Siheyuan/Quadrangle 
11.  战国：Warring States 
12.  风水：Fengshui/Geomantic Omen 
13.  铁饭碗：Iron Bowl 
14.  函授部：The Correspondence Department 
15.  集体舞：Group Dance 
16.  黄土高原：Loess Plateau 
17.  红白喜事：Weddings and Funerals 
18.  中秋节：Mid-Autumn Day 
19.  结婚证：Marriage Certificate 
20.  儒家文化：Confucian Culture 
21.  附属学校：Affiliated school 
22.  古装片：Costume Drama 
23.  武打片：Chinese Swordplay Movie 
24.  元宵：Tangyuan/Sweet Rice Dumpling (Soup) 
25.  一国两制：One Country, Two Systems 
26.  火锅：Hot Pot 
27.  四人帮：Gang of Four 
28.  《诗经》：The Book of Songs 
29.  素质教育：Essential-qualities-oriented Education 
30.  《史记》：Historical Records/Records of the Grand Historian 
31.  大跃进：Great Leap Forward (Movement) 
32.  《西游记》：The Journey to the West 
33.  除夕：Chinese New Year’s Eve/Eve of the Spring Festival 
34.  针灸：Acupuncture 
35.  唐三彩：Tri-color Pottery of the Tang Dynasty/ The Tang Tri-colored pottery 
36.  中国特色的社会主义：Chinese-charactered Socialist/Socialist with Chinese characteristics 
37.  偏旁：radical 
38.  孟子：Mencius 
39.  亭/阁： Pavilion/ Attic 
40.  大中型国有企业：Large and Medium-sized State-owned Enterprises 
41.  火药：gunpowder 
42.  农历：Lunar Calendar 
43.  印/玺：Seal/Stamp 
44.  物质精神文明建设：The Construction of Material Civilization and Spiritual Civilization 
45.  京剧：Beijing Opera/Peking Opera 
46.  秦腔：Crying of Qin People/Qin Opera 
47.  太极拳：Tai Chi 
48.  独生子女证：The Certificate of One-child 
49.  天坛：Altar of  Heaven in Beijing 
50.  小吃摊：Snack Bar/Snack Stand 
51.  红双喜：Double Happiness 
52.  政治辅导员：Political Counselor/School Counselor 
53.  春卷：Spring Roll(s) 
54.  莲藕：Lotus Root 
55.  追星族：Star Struck 
56.  故宫博物院：The Palace Museum 
57.  相声：Cross-talk/Comic Dialogue 
58.  下岗：Lay off/Laid off 
59.  北京烤鸭：Beijing Roast Duck 
60.  高等自学考试：Self-taught Examination of Higher Education 
61.  烟花爆竹：fireworks and firecracker 
62.  敦煌莫高窟：Mogao Caves 
63.  电视小品：TV Sketch/TV Skit 
64.  香港澳门同胞：Compatriots from Hong Kong and Macao 
65.  文化大革命：Cultural Revolution 
66.  长江中下游地区：The Mid-low Reaches of Yangtze River 
67.  门当户对：Perfect Match/Exact Match 
68.  《水浒》：Water Margin/Outlaws of the Marsh 
69.  中外合资企业：Joint Ventures 
70.  文房四宝（笔墨纸砚）："The Four Treasure of the Study" "Brush, Inkstick, Paper, and Inkstone", 
7.必知缩写
asl是Age, sex and location 的所写，年龄，性别和地址（国籍） lol是laugh out loud的缩写，意思是大声笑,笑的很开心的样子 
ppl=people
bbs=be back soon=很快回来 
thx=thanks  
ur=your  
asap=as soon as possible  
g2g = got to go  
ttyl = talk to you later  
brb = be right back  
bbl = be back later  
bio brb=上个厕所就回
afk = away from keyboard (away)  
u = you  
plz = please  
y = why  
w8 = wait  
l8er = later  
cya = see ya (later)  
nvm = nevermind  
nm = not much  
gl = good luck  
gf = girlfriend  
bf = boyfriend  
luv=love
RUOK=are you ok?
sp=support
cu=see u
cul8er= see you later
ft=faint
ic=i see
soho=small office home officer
btw=by the way
gn=gn8=gnight=good night=晚安 
nn=nite=晚安 
说明：一般第一个人常说gnight/gn8,然后第二个人用nite,后面的用nn什么的都可以了。不要问我为什么，约定俗成而已。
hiho=hola=yo=hi=hey=hellow=ello你好，大家好 
wuz up=sup=what's up=(原意：怎么样你？/有什么事儿嘛？)也可作为问好用(当然是比较熟的两个人之间的问候)，回答时有事说事，没事用"nothing/nothin much/not much/nm等回答就可以。
OMG=oh my god=我的天；我靠！ 
OMFG=oh my fucking god=我的老天；我靠靠； 
wtf=what the fuck=怎么会事！？；我日！；
OMGWTFBBQSOURCE !!!表震惊到了极致.  
n1=nice 1=nice one=漂亮 
pwnz=ownz=牛比！(例句：pwnz demo!;lefuzee ownz all the others!) 
rullz=强！(例句：lefuzee rullz!;you guyz rull!!!) 
you rock!=你牛比！
lmao=laughing my ass off=笑的屁股尿流 
rofl=roll on floor laughing=笑翻天了
roflmao=rofl+lmao=笑到爆了! 
语气强度排序:hehe<haha<lol<muwahaha<lmao<rofl<roflmao

---其他简写--- 
1,FU=f uck you=*你；滚 
2,STFU=Shut the f uck up!=他妈的给我闭嘴！ 
3,k=ok=okay=okie=好的，恩 
4,sux=suck的第3人称单数形势(例句：that sux)=sb；滥 
5,gimme=give me=给我 
6,xfer=transfer=传输 
7,em=them=他们的宾格 
8,thx=thanks=谢谢 
9,happy bday=happy b-day=happy birthday!=生日快乐 
10,dunno=dont know=不知道 
11,kinda=a little bit=有点(例句：The game is kinda hard for me.i kinda think i should get it done as soon as possible.) 
12,tho=though=虽然尽管(例句：That demo was very nice,kinda old tho.那个demo很不错，虽然有点老) 
13,plz=please=请 
14,cmon=c'mon=come on 
15,suka=s ucker suck(吮吸),er(表“人”)，吮吸的人...没天真到无邪的人都能明白了。 
16,enuff=enough=足够 
17,hax=hack=cheat=作弊，说谎(很地道时尚的词，老外用的比较多) 
18,ty=thank you 原本用的不多，不过现在又开始兴起来了 
19,conn=connection=线路,网络,网络类型 (例句:what conn do you have? / cable ) 
20,asap=as soon as possible 尽快 
21,imo=in my opinion 我认为 
22,smh=shake my head (摇头叹气) 
23,dayum=damn=dang 
24,ttyl=talk to you later 
25,b/c=because 
26,j/j=j/k=j/p=just joking, kidding, playing (开玩笑) 
27,w/=with 
28,w/o=without 
29,holla=来和我讲话，also, holla at yo boy, holla at yo girl etc. 
30,atcha=at you
31,gotcha?=got you?
 
---特殊用语--- 
1,w00t=woot=what=虾米？！主要表示what和yeah的意思，例如惊叹和兴奋。 
2,1337=l337=l33t=leet=elite=很强，超强的西西(例句：l33t demo;lefuzee is l337!!!!) 
3,lame=滥；衰 (例句:dude,thats the lamest thing ive ever heard.哥们，这是我听过的最sb的事情。) 
4,dude=d00d=(原意：花花公子)哥们，朋友 
5,pffffff=whatever=随便；爱咋咋地； ("f"的多少和"pffffffff"的长短代表你的感情激烈程度) 
6,n00b=newbie=新人，新手；小嫩手 
7,sry=不好意思;
---表情符--- 
:  ) 
; D 
; o 
; o 
: > --- (gay smile) 
\o/ --- (欢庆) 
\\o --- (欢庆) 
o// --- (欢庆) 
D: --- (吃惊) 
Oo=O_o=虾米！(挣大眼睛表示惊叹) 
<3=心，表示喜爱
2=to
4=for
B=be
U=you
R=are
C=see
AFK=away from keyboard
ASAP=as soon as possible
BTW=by the way
BBIAM=be back in a minute
CU=see you
CUL=see you later
CWYL=char with you later
FE=for example
F2F=face to face
FYI=for your information（供参考）
FYR=for your reference
FU=...这个不用说了吧 0_0
GL=good luck
GTG=got to go
GTH=go to hell
HTH=hit the hay(睡觉去了，hay:床）
IAC=in any case
ILY=i love you
IMO=in my opinion
KIT=keep in touch
NRN=no reply necessary(不必回信)
NP=no problem
OMG=oh my god
OIC=oh i see
OTOH=on the other hand
ORLY=oh really?
PEM=privacy enhanced mail(保密邮件)
RSN=real soon now(马上)
TM=trust me
WB=welcome back
WTG=way to go
WYP=what's your problem?
8.必备成语
1.爱屋及乌 Love me, love my dog. 
2.百闻不如一见 （眼见为实 ）Seeing is believing.
3.比上不足比下有余 worse off than some, better off than many; to fall short of the best, but be better than the worst. 
4.笨鸟先飞 A slow sparrow should make an early start. 
5.不眠之夜 white night 
6.不以物喜不以己悲 not pleased by external gains, not saddened by personnal losses 
7.不遗余力 spare no effort; go all out; do one's best 
8.不打不成交 No discord, no concord. 
9.拆东墙补西墙 rob Peter to pay Paul 
10.辞旧迎新 bid farewell to the old and usher in the new; ring out the old year and ring in the new 
11.大事化小小事化了 try first to make their mistake sound less serious and then to reduce it to nothing at all 
12.大开眼界 open one's eyes; broaden one's horizon; be an eye-opener 
13.国泰民安 The country flourishes and people live in peace 
14.过犹不及 going too far is as bad as not going far enough; beyond is as wrong as falling short; too much is as bad as too little 
15.功夫不负有心人 Everything comes to him who waits. 
16.好了伤疤忘了疼 once on shore, one prays no more 
17.好事不出门恶事传千里 Good news never goes beyond the gate, while bad news spread far and wide. 
18.和气生财 Harmony brings wealth. 
19.活到老学到老 One is never too old to learn. 
20.既往不咎 let bygones be bygones 
21.金无足赤人无完人 Gold can't be pure and man can't be perfect. 
22.金玉满堂 Treasures fill the home. 
23.脚踏实地 be down-to-earth 
24.脚踩两只船 sit on the fence 
25.君子之交淡如水 the friendship between gentlemen is as pure as crystal; a hedge between keeps friendship green 
26.老生常谈陈词滥调 cut and dried, cliché 
27.礼尚往来 Courtesy calls for reciprocity. 
28.留得青山在不怕没柴烧 Where there is life, there is hope. 
29.马到成功 achieve immediate victory; win instant success 
30.名利双收 gain in both fame and wealth 
31.茅塞顿开 be suddenly enlightened 
32.没有规矩不成方圆 Nothing can be accomplished without norms or standards. 33.每逢佳节倍思亲 On festive occasions more than ever one thinks of one's dear ones far away.It is on the festival occasions when one misses his dear most. 
34.谋事在人成事在天 The planning lies with man, the outcome with Heaven. Man proposes, God disposes. 
35.弄巧成拙 be too smart by half; Cunning outwits itself 
36.拿手好戏 masterpiece 
37.赔了夫人又折兵 throw good money after bad 
38.抛砖引玉 a modest spur to induce others to come forward with valuable contributions; throw a sprat to catch a whale 
39.破釜沉舟 cut off all means of retreat；burn one‘s own way of retreat and be determined to fight to the end
40.抢得先机 take the preemptive opportunities 
41.巧妇难为无米之炊 If you have no hand you can't make a fist. One can't make bricks without straw.
42.千里之行始于足下 a thousand-li journey begins with the first step--the highest eminence is to be gained step by step 
43.前事不忘后事之师 Past experience, if not forgotten, is a guide for the future. 44.前人栽树后人乘凉 One generation plants the trees in whose shade another generation rests.One sows and another reaps. 
45.前怕狼后怕虎 fear the wolf in front and the tiger behind hesitate in doing something 
46.强龙难压地头蛇 Even a dragon (from the outside) finds it hard to control a snake in its old haunt - Powerful outsiders can hardly afford to neglect local bullies. 
47.强强联手 win-win co-operation 
48.瑞雪兆丰年 A timely snow promises a good harvest
49.人之初性本善 Man's nature at birth is good. 
50.人逢喜事精神爽 Joy puts heart into a man. 
51.人海战术 huge-crowd strategy 
52.世上无难事只要肯攀登 Where there is a will, there is a way. 
53.世外桃源 a fictitious land of peace away from the turmoil of the world; 
54.死而后已 until my heart stops beating 
55.岁岁平安 Peace all year round. 
56.上有天堂下有苏杭 Just as there is paradise in heaven, ther are Suzhou and Hangzhou on earth 
57.塞翁失马焉知非福 Misfortune may be an actual blessing. 
58.三十而立 A man should be independent at the age of thirty.At thirty, a man should be able to think for himself. 
59.升级换代 updating and upgrading (of products)
60.四十不惑 Life begins at forty. 
61.谁言寸草心报得三春晖 Such kindness of warm sun, can't be repaid by grass. 62.水涨船高 When the river rises, the boat floats high. 
63.时不我待Time and tide wait for no man. 
64.杀鸡用牛刀break a butterfly on the wheel 
65.实事求是seek truth from facts; be practical and realistic; be true to facts 
66.说曹操,曹操到Talk of the devil and he comes. 
67.实话实说speak the plain truth; call a spade a spade; tell it as it is 
68.实践是检验真理的唯一标准Practice is the sole criterion for testing truth. 
69.山不在高，有仙则名'No matter how high the mountain is, its name will spread far and wide if there is a fairy; ' 
70.韬光养晦hide one's capacities and bide one's time 
71.糖衣炮弹sugar-coated bullets 
72.天有不测风云Anything unexpected may happen. a bolt from the blue 
73.团结就是力量Unity is strength. 
74.“跳进黄河洗不清”'eve if one jumped into the Yellow River, one can not wash oneself clean--there's nothing one can do to clear one's name ' 
75.歪风邪气unhealthy practices and evil phenomena 
76.物以类聚，人以群分Birds of a feather flock together. 
77.往事如风'The past has vanished (from memory) like wind.; What in past, is pas 
78.望子成龙hold high hopes for one's child 
79.屋漏又逢连阴雨Misfortunes never come singly. When it rains it pours. 
80.文韬武略military expertise; military strategy 
81.唯利是图draw water to one's mill 
82.无源之水,无本之木water without a source, and a tree wiithout roots 
83.无中生有make create something out of nothing 
84.无风不起浪There are no waves without wind. There's no smoke without fire. 85.徇私枉法bend the law for the benefit of relatives or friends 
86.新官上任三把火a new broom sweeps clean 
87.虚心使人进步,骄傲使人落后Modesty helps one go forward, whereas conceit makes one lag behind. 
88. 蓄势而发accumulate strength for a take-off 
89.心想事成May all your wish come true 
90.心照不宣have a tacit understanding; give tacit consent; tacit understanding 91.先入为主First impressions are firmly entrenched. 
92.先下手为强catch the ball before the bound 
93.像热锅上的蚂蚁like an ant on a hot pan 
94.现身说法warn people by taking oneself as an example 
95.息事宁人pour oil on troubled waters 
96.喜忧参半mingled hope and fear 
97.循序渐进step by step 
98.一路平安，一路顺风speed somebody on their way; speed the parting guest 
99.严以律己,宽以待人be strict with oneself and lenient towards others 
100鱼米之乡
101.有情人终成眷属'Jack shall have Jill, all shall be well.' 
102.有钱能使鬼推磨Money makes the mare go. Money talks. 
103. 有识之士people of vision 
104.有勇无谋use brawn rather than brain 
105.有缘千里来相会Separated as we are thousands of miles apart, we come together as if by predestination. 
106.与时俱进advance with times 
107.以人为本people oriented; people foremost 
108.因材施教teach students according to their aptitude 
109.欲穷千里目，更上一层楼'to ascend another storey to see a thousand miles further; Ascend further, were you to look farther; Would eye embrace a thousand miles? Go up, one flight.' a land of milk and honey 
110.欲速则不达Haste does not bring success. 
111. 优胜劣汰survival of the fittest 
112.英雄所见略同Great minds think alike. 
113.冤家宜解不宜结Better make friends than make enemies. 
114.冤假错案'cases in which people were unjustly, falsely or wrongly charged or sentenced; unjust, false or wrong cases' 
115.一言既出，驷马难追A real man never goes back on his words. 
116.招财进宝Money and treasures will be plentiful 
117.债台高筑become debt-ridden 
118.致命要害Achilles' heel 
119. 众矢之的target of public criticism 
120.知己知彼,百战不殆Know the enemy and know yourself, and you can fight a hundred battles with no danger of defeat. 
121. 纸上谈兵be an armchair strategist 
122.纸包不住火Truth will come to light sooner or later. 
123.左右为难between the devil and the deep blue sea
9.女生用品
一，化妆品/护肤品/洗涤
护肤: skin care  
洗面奶: facial cleanser/face wash(foaming,milky,cream,gel)  
爽肤水: toner/astringent  
紧肤水：firming lotion  
柔肤水：toner/smoothing toner （facial mist/facial spray/complexion mist）  
护肤霜: moisturizers and creams  
保湿：moisturizer  
隔离霜，防晒：sun screen/sun block  
美白：whitening  
露：lotion，霜：cream  
日霜：day cream  
晚霜：night cream  
眼部gel: eye gel  
面膜: facial mask/masque  
眼膜: eye mask  
护唇用：lip care  
口红护膜：lip coat  
磨砂膏: facial scrub  
去黑头: (deep) pore cleanser/striper pore refining  
去死皮: exfoliating scrub  
润肤露（香体乳）:lotion/moisturizer  
护手霜: hand lotion/moisturizer  
沐浴露: wash
二，化妆品/护肤品功能  

acne/spot（青春痘用品）  
active（赋活用）  
after sun（日晒后用品）  
alcohol-free（无酒精）  
anti-（抗、防）  
anti-wrinkle（抗老防皱）  
balancing（平衡酸硷）  
clean-/purify-（清洁用）  
combination（混合性皮肤）  
dry（干性皮肤）  
essence（精华液）  
facial（脸部用）  
fast/quick dry（快干）  
firm（紧肤）  
foam（泡沫）  
gentle（温和的）  
hydra-（保湿用）  
long lasting（持久性）  
milk（乳）  
mult-（多元）  
normal（中性皮肤）  
nutritious（滋养）  
oil-control（抑制油脂）  
oily（油性皮肤）  
pack（剥撕式面膜）  
peeling（敷面剥落式面膜）  
remover（去除、卸妆）  
repair（修护）  
revitalite（活化）  
scrub（磨砂式(去角质)）  
sensitive（敏感性皮肤）  
solvent（溶解）  
sun block（防晒用）  
toning lotion（化妆水）  
trentment（修护）  
wash（洗）  
waterproof（防水）
三，化妆品/彩妆  

彩妆: cosmetics  
遮瑕膏: concealer  
修容饼：shading powder  
粉底: foundation (compact,stick)  
粉饼: pressed powder  
散粉：loose powder  
闪粉：shimmering powder/glitter  
眉粉: brow powder  
眉笔：brow pencil  
眼线液（眼线笔）：liquid eye liner, eye liner  
眼影: eye shadow  
睫毛膏: mascara  
唇线笔: lip liner  
唇膏: lip color/lipstick（笔状 lip pencil，膏状 lip lipstick，盒装 lip color/lip gloss）  
唇彩: lip gloss/lip color  
腮红: blush  
卸装水: makeup remover  
卸装乳: makeup removing lotion  
帖在身上的小亮片: art  
指甲: manicure/pedicure  
指甲油: nail polish/color/enamel  
去甲油：nail polish remover  
护甲液：nail saver  
发: hair products/accessories  
洗发水: shampoo  
护发素: hair conditioner  
锔油膏: conditioning hairdressing/hairdressing gel /treatment  
摩丝: mousse  
发胶: styling gel  
染发: hair color  
冷烫水: perm/perming formula  
卷发器: rollers/perm rollers
四，化妆品/化妆工具  

工具: cosmetic applicators/accessories  
粉刷: cosmetic brush, face brush  
粉扑: powder puffs  
海绵扑: sponge puffs  
眉刷: brow brush  
睫毛夹: lash curler  
眼影刷: eye shadow brush/shadow applicator  
口红刷: lip brush  
胭脂扫: blush brush  
转笔刀: pencil sharpener  
电动剃毛器: electric shaver-for women  
电动睫毛卷: electric lash curler  
描眉卡: brow template  
纸巾: facial tissue  
吸油纸: oil-absorbing sheets  
化装棉: cotton pads  
棉签: q-tips
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
　  1、eye cream/eye care/eye gel：眼霜或者眼部保养品或者眼胶
　　2、masque：面膜,是面膜产品的通称. 
　　面膜的其他表示方法有*mask-面具*pack-外盒,包
　　3、day&night：指白天专用的产品和晚上专用的产品
　　4、exfoliate：剥落,脱落.一般看到exfoliate基本上就是去角质的产品了. 
　　其他表示方法:scrub去除杂质
　　5、essence：精华,要素;指精华液,美容液,精华露. 
　　essential-精华的;soul-精髓;extract-萃取精华
　　6、lotion：化妆水,洗涤剂.英文法文表示一致,都是lotion 
　　有些品牌也用lotion作为乳液的用词,不过严格来讲,最好是在lotion前面加上milk(乳液,乳状物),或者milky(乳状的),也就是milk/milky lotion
　　化妆水的其他用语:toner;tonic;water 
　　乳液的其他用语:fluid-流动的,液体(英文法文通用);liquid-液体物质
　　7、foam：泡沫,或者可以挤出来的泡沫,可以产生泡沫的产品
　　8、soap：肥皂,块状的产品
　　肥皂类其他用语:bar 
    9、make up remover：卸妆
　　卸妆的其他用语:cleanser, cleansing, clean off, clean out都有清洁,扫除的意思,但有时会跟洗脸产品的标示有重叠,要留意是否注明[可以清除彩妆]
　　10、balm：香油,芳香性树脂,大多指护唇油(罐装的唇膏)
　　护唇膏的其他用语:lipsalve-嘴唇用油膏;lip ointment-唇用软膏
　　11、shake well before use：使用前请先摇匀
　　通常这一类产品都含有不同密度的物质,所以要先摇匀
　　摇匀的其他用语:brandish-摇动;jiggle-轻轻晃动;joggle-轻摇
　　12、tissue-off：用完以后要以面纸或者化妆棉,擦掉的产品
　　擦拭的其他用语:well-off;brush;wipe off
　　需要[剥,撕]的其他用语eel off
　　13、wash-off：水洗,用后要洗掉的
　　水洗的其他用语:water-off;rinsing-off;washable;sweep
　　14、pat：轻拍,轻抚,轻压
　　拍打的其他用语ab-以手按压;flap-拍打,扑打
　　有些产品需要稍加画圆,按摩.外文是:massage-onto-在肌肤上面按摩;circular movement-画圆移动
～～～～～～～～～～～～～～～～～～～
nail polish 指甲油  
cosmetics case 化妆箱  
high heels 高跟鞋  
gloves 手套  
wrist watch 手表  
belt 腰带  
pendant 项饰  
necklace 项链  
neck scarf 围巾  
earrings 耳环  
bracelet 手链, 手镯  
tie 领带  
cuff links 袖扣  
ascot 宽领带  
pocket watch 表袋  
hair net 发网  
shampoo 洗发水  
cream rinse 营养发水  
hair spray 发胶  
powder puff 粉扑  
compact 带镜粉盒  
astringent 化妆水  
perfume 香水  
skin milk 乳液  
cold cream 油底霜  
atomizer 喷雾式香水  
clip 夹子  
hand mirror 手镜  
bobby pin 发夹  
false eyelash 假睫毛  
lipstick 口红  
wig 假发  
tie pin 领带夹  
tissue 面纸  
purse 手提包  
brooch 胸针  
shawl 披肩  
neckerchief 领巾 
毛孔：pore
T型区：T-zone or T area


#T=正如你所说
As you are aware,
#